export const REVIEW_PRESERVED_FIELDS = [
  'concept_id',
  'concept_name',
  'concept_type',
  'definition',
  'definition_zh',
  'aliases',
  'evidence',
  'confidence',
  'review_status',
  'review_flags',
  'reviewed_by',
  'reviewed_at',
  'review_notes',
  'canonical_concept_id',
  'canonical_concept_name',
];

export const REVIEW_STATUSES = ['unreviewed', 'approved', 'edited', 'flagged', 'rejected', 'ambiguous', 'needs_revision', 'reviewed'];

const chapter6TraitResponseKeys = [
  'chapter6::formula_6.4::defined::R_{z}',
  'chapter6::formula_6.6::defined::R_{z}',
  'chapter6::formula_6.7b::defined::R_{z}',
  'chapter6::formula_6.7c::defined::R_{z}',
  'chapter6::formula_6.8::defined::R_{z}',
  'chapter6::formula_6.9b::defined::R_{z}',
  'chapter6::formula_6.16b::defined::R_{z}',
  'chapter6::formula_6.16f::defined::R_{z}',
  'chapter6::formula_6.24a::defined::R_{z}',
  'chapter6::formula_6.24b::defined::R_{z}',
  'chapter6::formula_6.25a::defined::R_{z}',
  'chapter6::formula_6.25b::defined::R_{z}',
  'chapter6::formula_6.25c::defined::R_{z}',
  'chapter6::formula_6.26::defined::R_{z}',
  'chapter6::formula_6.27::defined::R_{z}',
  'chapter6::formula_6.30a::defined::R_{z}',
];

const chapter6FitnessResponseKeys = [
  'chapter6::formula_6.18a::defined::R_{W}',
  'chapter6::formula_6.18c::defined::R_{W}',
  'chapter6::formula_6.18g::defined::R_{W}',
  'chapter6::formula_6.19::defined::R_{W}',
  'chapter6::formula_6.22a::defined::R_{W}',
  'chapter6::formula_6.22b::defined::R_{W}',
];

const chapter6RelativeFitnessResponseKeys = [
  'chapter6::formula_6.17c::defined::R_{w}',
  'chapter6::formula_6.21a::defined::R_{w}',
  'chapter6::formula_6.21b::defined::R_{w}',
];

function chapter6ResponseCalibration({ conceptName, definition, aliases, reviewNotes, confidence = 0.94 }) {
  return {
    concept_name: conceptName,
    concept_type: 'quantity_concept',
    definition,
    aliases,
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: reviewNotes,
    confidence,
  };
}

const chapter6ResponseCalibrations = [
  ...chapter6TraitResponseKeys.map((stableKey) => [stableKey, chapter6ResponseCalibration({
    conceptName: 'Trait Response',
    definition: 'The response to selection in the focal trait z, expressed in this chapter through Price-equation, breeder-equation, and Robertson covariance forms.',
    aliases: ['R_{z}', 'R_z', 'Trait Response', 'Response in Trait z'],
    reviewNotes: 'Rule calibration: chapter 6 repeatedly uses R_z for the focal trait response; keep the public concept name stable across equivalent forms.',
    confidence: 0.95,
  })]),
  ...chapter6FitnessResponseKeys.map((stableKey) => [stableKey, chapter6ResponseCalibration({
    conceptName: 'Fitness Response',
    definition: 'The response to selection in absolute mean fitness, used in Fisher fundamental-theorem derivations and environmental decompositions.',
    aliases: ['R_{W}', 'R_W', 'Fitness Response', 'Response in Absolute Fitness'],
    reviewNotes: 'Rule calibration: chapter 6 repeatedly uses R_W for the response in absolute fitness; keep the public concept name stable across equivalent forms.',
    confidence: 0.95,
  })]),
  ...chapter6RelativeFitnessResponseKeys.map((stableKey) => [stableKey, chapter6ResponseCalibration({
    conceptName: 'Relative Fitness Response',
    definition: 'The response to selection in relative fitness, scaled from absolute fitness response or decomposed into genetic and average-effect-change terms.',
    aliases: ['R_{w}', 'R_w', 'Relative Fitness Response', 'Response in Relative Fitness'],
    reviewNotes: 'Rule calibration: chapter 6 uses R_w for the response in relative fitness, distinct from the absolute-fitness response R_W.',
    confidence: 0.94,
  })]),
];

function chapter6RuleCalibration({ conceptName, conceptType = 'quantity_concept', definition, aliases, reviewNotes, confidence = 0.92, flags = ['llm_validated'] }) {
  return {
    concept_name: conceptName,
    concept_type: conceptType,
    definition,
    aliases,
    review_status: 'edited',
    review_flags: flags,
    reviewed_by: 'auto_rule_fix',
    review_notes: reviewNotes,
    confidence,
  };
}

const chapter6OffspringParentRegressionKeys = [
  'chapter6::formula_6.30b::used::\\beta_{\\overline{z}|z}',
  'chapter6::formula_6.31b::used::\\beta_{\\overline{z}|z}',
  'chapter6::formula_6.32::used::\\beta_{\\overline{z}|z}',
  'chapter6::formula_6.33e::used::\\beta_{\\overline{z}|z}',
  'chapter6::formula_6.33f::used::\\beta_{\\overline{z}|z}',
  'chapter6::formula_6.35::defined::\\beta_{\\overline{z}|z}',
  'chapter6::formula_6.40::used::\\beta_{\\overline{z},z}',
];

const chapter6PreselectionRegressionKeys = [
  'chapter6::formula_6.35::used::\\beta_{\\overline{z}^{\\circ}|z}',
  'chapter6::formula_6.36a::used::\\beta_{\\overline{z}^{\\circ}|z}',
  'chapter6::formula_6.39::used::\\beta_{\\overline{z}^{\\circ}|z}',
];

const chapter6UnselectedOffspringTraitKeys = [
  'chapter6::formula_6.38::used::\\overline{z}_{i}^{\\circ}',
  'chapter6::formula_6.39::used::\\overline{z}^{\\circ}',
  'chapter6::formula_6.40::used::\\overline{z}^{\\circ}',
];

const chapter6PriceFrameCalibrations = [
  ['chapter6::formula_6.18f::used::\\Delta', chapter6RuleCalibration({
    conceptName: 'Allele-Frequency Change Operator',
    conceptType: 'operator_or_function',
    definition: 'The finite-difference operator used with allele frequency p to express the one-generation change Delta p under selection.',
    aliases: ['\\Delta', 'Delta', 'Allele-Frequency Change Operator'],
    reviewNotes: 'Rule calibration from Formula 6.18f: Delta is the change operator in Delta p, not a standalone raw symbol concept.',
    confidence: 0.9,
  })],
  ['chapter6::formula_6.18f::used::p', chapter6RuleCalibration({
    conceptName: 'Allele Frequency',
    definition: 'The frequency of the focal allele in the one-locus fitness example used to derive Fisher-style fitness response.',
    aliases: ['p', 'Allele Frequency'],
    reviewNotes: 'Rule calibration from Formula 6.18f and nearby Wright-formula text: p is the allele frequency being changed by selection.',
    confidence: 0.92,
  })],
  ['chapter6::formula_6.24b::used::\\beta_{A_{z}|A_{w}}', chapter6RuleCalibration({
    conceptName: 'Trait-on-Fitness Breeding-Value Regression',
    definition: 'The regression coefficient of trait breeding value A_z on fitness breeding value A_w, converting fitness breeding-value response into trait response.',
    aliases: ['\\beta_{A_{z}|A_{w}}', 'beta_Az_given_Aw', 'Trait-on-Fitness Breeding-Value Regression'],
    reviewNotes: 'Rule calibration from Formula 6.24b: the same regression coefficient is defined explicitly in Formula 6.24c.',
    confidence: 0.94,
  })],
  ['chapter6::formula_6.30b::defined::\\overline{z}_{i}', chapter6RuleCalibration({
    conceptName: 'Mean Offspring Trait Value',
    definition: 'The mean offspring trait value for parental class i in the parent-offspring regression used by the Price-frame breeder equation.',
    aliases: ['\\overline{z}_{i}', 'Mean Offspring Trait Value', 'Offspring Class Trait Mean'],
    reviewNotes: 'Rule calibration from Formula 6.30b: overline z_i is the offspring trait mean regressed on parental trait z_i.',
    confidence: 0.92,
  })],
  ['chapter6::formula_6.30b::used::e_{\\overline{z},i}', chapter6RuleCalibration({
    conceptName: 'Offspring Trait Regression Residual',
    definition: 'The residual deviation of offspring mean trait value after the parent-offspring regression on parental trait z_i.',
    aliases: ['e_{\\overline{z},i}', 'e_overline_z_i', 'Offspring Trait Regression Residual'],
    reviewNotes: 'Rule calibration from Formula 6.30b: e_overline_z,i is the residual in the offspring-on-parent regression.',
    confidence: 0.91,
  })],
  ['chapter6::formula_6.33e::used::\\sigma_{\\overline{z}}^2', chapter6RuleCalibration({
    conceptName: 'Offspring Trait Variance',
    definition: 'The variance of offspring mean trait values appearing in the partial-covariance regression identity.',
    aliases: ['\\sigma_{\\overline{z}}^2', 'sigma_overline_z_squared', 'Offspring Trait Variance'],
    reviewNotes: 'Rule calibration from Formula 6.33e: sigma_overline_z^2 is the variance term in the partial covariance expression.',
    confidence: 0.9,
  })],
  ...chapter6OffspringParentRegressionKeys.map((stableKey) => [stableKey, chapter6RuleCalibration({
    conceptName: 'Offspring-on-Parent Trait Regression',
    definition: 'The regression slope of offspring mean trait value on parental trait value, used to frame the breeder equation inside the Price equation.',
    aliases: ['\\beta_{\\overline{z}|z}', '\\beta_{\\overline{z},z}', 'Offspring-on-Parent Trait Regression'],
    reviewNotes: 'Rule calibration: chapter 6 uses beta_overline_z|z and beta_overline_z,z for the offspring-on-parent regression slope in the Price-frame breeder equation.',
    confidence: 0.92,
  })]),
  ...chapter6PreselectionRegressionKeys.map((stableKey) => [stableKey, chapter6RuleCalibration({
    conceptName: 'Preselection Offspring-on-Parent Regression',
    definition: 'The regression slope of offspring trait before selection on parental trait, used in Heywood-style decompositions of the breeder equation.',
    aliases: ['\\beta_{\\overline{z}^{\\circ}|z}', 'beta_preselection_offspring_given_parent', 'Preselection Offspring-on-Parent Regression'],
    reviewNotes: 'Rule calibration from Formulas 6.35, 6.36a, and 6.39: beta_overline_z_circ|z is the before-selection parent-offspring regression slope.',
    confidence: 0.91,
  })]),
  ...chapter6UnselectedOffspringTraitKeys.map((stableKey) => [stableKey, chapter6RuleCalibration({
    conceptName: 'Unselected Offspring Trait Value',
    definition: 'The offspring trait value or mean offspring trait value evaluated before selection on parents, used in the Heywood decomposition.',
    aliases: ['\\overline{z}^{\\circ}', '\\overline{z}_{i}^{\\circ}', 'Unselected Offspring Trait Value'],
    reviewNotes: 'Rule calibration from Formulas 6.38-6.40: overline z circ denotes offspring trait value before selection on parents.',
    confidence: 0.9,
  })]),
];

const chapter21FamilyResponseKeys = [
  'chapter21::formula_21.1a::defined::R_{y}',
  'chapter21::formula_21.1b::defined::R_{y}',
  'chapter21::formula_21.2a::defined::R_{y}',
  'chapter21::formula_21.3a::defined::R_{y}',
  'chapter21::formula_21.3b::defined::R_{y}',
  'chapter21::formula_21.4a::defined::R_{y}',
  'chapter21::formula_21.4b::defined::R_{y}',
];

const chapter21FamilyResponseCalibrations = chapter21FamilyResponseKeys.map((stableKey) => [stableKey, chapter6RuleCalibration({
  conceptName: 'Family-Based Response to Selection',
  definition: 'The predicted change in mean trait y under family-based selection, expressed through breeder-equation and covariance forms.',
  aliases: ['R_{y}', 'R_y', 'Family-Based Response to Selection', 'Response to Selection on Trait y'],
  reviewNotes: 'Rule calibration: chapter 21 uses R_y throughout this subsection for the family-based response to selection; keep one public concept name across equivalent formulas.',
  confidence: 0.94,
})]);

const releaseQualityCalibrations = [
  ['chapter2::formula_2.11a::defined::\\bar{t}_{a}', chapter6RuleCalibration({
    conceptName: 'Mean Allele Absorption Time',
    definition: 'The mean time until an allele starting at frequency p0 is either lost or fixed in the population.',
    aliases: ['\\bar{t}_{a}', 't_a', 'Mean Allele Absorption Time'],
    reviewNotes: 'Rule calibration from Formula 2.11a local text: t_a is the allele absorption time, not a generic mean time.',
    confidence: 0.94,
  })],
  ['chapter2::formula_2.11d::defined::\\overline{t}_{a}', chapter6RuleCalibration({
    conceptName: 'Mean Allele Absorption Time',
    definition: 'The fixation-probability-weighted mean time until the neutral allele is either fixed or lost.',
    aliases: ['\\overline{t}_{a}', 't_a', 'Mean Allele Absorption Time'],
    reviewNotes: 'Rule calibration from Formula 2.11d: t_a combines conditional fixation and loss times into the absorption time.',
    confidence: 0.94,
  })],
  ['chapter2::formula_2.38::defined::\\bar{t}_{c}', chapter6RuleCalibration({
    conceptName: 'Mean Pairwise Coalescence Time',
    definition: 'The expected coalescence time for two randomly sampled genes.',
    aliases: ['\\bar{t}_{c}', 't_c', 'Mean Pairwise Coalescence Time'],
    reviewNotes: 'Rule calibration from Formula 2.38: t_c is the pairwise coalescence time.',
    confidence: 0.94,
  })],
  ['chapter2::formula_2.40::defined::\\bar{t}_{n}', chapter6RuleCalibration({
    conceptName: 'Mean Lineage-Merging Time',
    definition: 'The expected time for n random lineages to merge into n-1 lineages in the coalescent process.',
    aliases: ['\\bar{t}_{n}', 't_n', 'Mean Lineage-Merging Time'],
    reviewNotes: 'Rule calibration from Formula 2.40: t_n is the expected waiting time to the next lineage merger.',
    confidence: 0.94,
  })],
  ['chapter2::formula_2.45a::defined::\\bar{t}_{0}', chapter6RuleCalibration({
    conceptName: 'Mean Within-Deme Coalescence Time',
    definition: 'The mean coalescence time between random gene pairs sampled within demes under the island migration model.',
    aliases: ['\\bar{t}_{0}', 't_0', 'Mean Within-Deme Coalescence Time'],
    reviewNotes: 'Rule calibration from Formula 2.45a: t_0 is the within-deme coalescence time, equal to 2Nd generations.',
    confidence: 0.94,
  })],
  ['chapter7::formula_7.46::defined::\\bar{t}_{e}', chapter6RuleCalibration({
    conceptName: 'Mean Establishment Time',
    definition: 'The mean waiting time to establish the novel ab type through the two sequential mutational steps.',
    aliases: ['\\bar{t}_{e}', 't_e', 'Mean Establishment Time'],
    reviewNotes: 'Rule calibration from Formula 7.46: t_e is the establishment time for the novel haplotype.',
    confidence: 0.94,
  })],
  ['chapter7::formula_7.51::defined::\\bar{t}_{e}', chapter6RuleCalibration({
    conceptName: 'Mean Establishment Time',
    definition: 'The approximate mean establishment time when the intermediate mutation is effectively neutral.',
    aliases: ['\\bar{t}_{e}', 't_e', 'Mean Establishment Time'],
    reviewNotes: 'Rule calibration from Formula 7.51: t_e remains the establishment time under the effectively neutral intermediate case.',
    confidence: 0.94,
  })],
];

export const CONCEPT_CALIBRATIONS = new Map([
  ...chapter6ResponseCalibrations,
  ...chapter6PriceFrameCalibrations,
  ...chapter21FamilyResponseCalibrations,
  ...releaseQualityCalibrations,
  ['chapter6::formula_6.8::used::l', {
    concept_name: 'Array Alignment Marker',
    concept_type: 'math_concept',
    definition: 'A LaTeX array-column marker from the piecewise display, not a biological or mathematical concept in the formula.',
    aliases: ['l', 'array l', 'Array Alignment Marker'],
    review_status: 'rejected',
    review_flags: ['formula_or_symbol_artifact', 'llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration: Formula 6.8 uses {l} as the LaTeX array alignment specifier, so it must not appear as a concept node.',
    confidence: 0.99,
  }],
  ['chapter6::formula_6.9a::used::e_{i}', {
    concept_name: 'Offspring Trait Regression Residual',
    concept_type: 'quantity_concept',
    definition: 'The residual deviation in the mean offspring trait value for midparent class i after the offspring trait is regressed on the midparent trait.',
    aliases: ['e_{i}', 'e_i', 'Offspring Trait Regression Residual', 'Midparent-Offspring Residual'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration from Formula 6.9a and DeepSeek retry: e_i is the residual in the midparent-offspring regression, not a raw symbol concept.',
    confidence: 0.91,
  }],
  ['chapter6::formula_6.16c::defined::h^{2}', {
    concept_name: 'Narrow-Sense Heritability',
    concept_type: 'quantity_concept',
    definition: 'The proportion of trait variance attributed to additive genetic variance, here evaluated for the one-locus dominance example.',
    aliases: ['h^{2}', 'h^2', 'Narrow-Sense Heritability', 'Heritability'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration: Formula 6.16c defines h^2 as additive genetic variance divided by total genetic variance in the breeder-equation example.',
    confidence: 0.95,
  }],
  ['chapter6::formula_6.17b::defined::R_W', {
    concept_name: 'Fitness Response',
    concept_type: 'quantity_concept',
    definition: 'The response to selection in absolute fitness, equal here to the additive genetic variance in fitness divided by mean fitness.',
    aliases: ['R_W', 'Fitness Response', 'Response in Fitness'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration from Formula 6.17b: R_W is the Fisher-style response in absolute fitness, not a raw symbol node.',
    confidence: 0.95,
  }],
  ['chapter6::formula_6.20b::defined::R_{A_{W}}', {
    concept_name: 'Fitness Breeding-Value Response',
    concept_type: 'quantity_concept',
    definition: 'The between-generation change in the mean breeding value for fitness, decomposed with the Price equation into additive genetic variance and transmission terms.',
    aliases: ['R_{A_{W}}', 'R_AW', 'Fitness Breeding-Value Response', 'Mean Fitness Breeding-Value Change'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration from Formula 6.20b local text: R_AW is the response in mean breeding value for fitness.',
    confidence: 0.94,
  }],
  ['chapter6::formula_6.20b::used::\\epsilon_{i}', {
    concept_name: 'Absolute Fitness Residual',
    concept_type: 'quantity_concept',
    definition: 'The residual component of absolute fitness after separating the additive breeding value for fitness in the decomposition W_i = A_i + epsilon_i.',
    aliases: ['\\epsilon_{i}', 'epsilon_i', 'Absolute Fitness Residual', 'Fitness Breeding-Value Residual'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration from Formula 6.20b: epsilon_i is the non-additive residual in absolute fitness, uncorrelated with A_i by construction.',
    confidence: 0.92,
  }],
  ['chapter6::formula_6.24c::defined::\\beta_{A_{z}|A_{w}}', {
    concept_name: 'Trait-on-Fitness Breeding-Value Regression',
    concept_type: 'quantity_concept',
    definition: 'The regression coefficient of trait breeding value A_z on fitness breeding value A_w, equal to their covariance divided by the variance of A_w.',
    aliases: ['\\beta_{A_{z}|A_{w}}', 'beta_Az_given_Aw', 'Trait-on-Fitness Breeding-Value Regression'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration from Formula 6.24c: beta_Az|Aw converts fitness breeding-value change into trait breeding-value response.',
    confidence: 0.94,
  }],
  ['chapter6::formula_6.19::used::O', {
    concept_name: 'Big-O Remainder',
    concept_type: 'math_concept',
    definition: 'The asymptotic remainder term collecting third-order and higher terms in the weak-selection approximation.',
    aliases: ['O', 'O(s^3)', 'Big-O Remainder'],
    review_status: 'rejected',
    review_flags: ['formula_or_symbol_artifact', 'llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration: the O(s^3) term records approximation order and should not become a public concept node.',
    confidence: 0.97,
  }],
  ['chapter6::formula_6.27::used::O', {
    concept_name: 'Big-O Remainder',
    concept_type: 'math_concept',
    definition: 'The asymptotic remainder term collecting second-order and higher terms in the weak-selection approximation.',
    aliases: ['O', 'O(s^2)', 'Big-O Remainder'],
    review_status: 'rejected',
    review_flags: ['formula_or_symbol_artifact', 'llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration: the O(s^2) term records approximation order and should not become a public concept node.',
    confidence: 0.97,
  }],
  ['chapter6::formula_6.29::used::e_{w}', {
    concept_name: 'Fitness Breeding-Value Residual',
    concept_type: 'quantity_concept',
    definition: 'The residual component of relative fitness after separating out the fitness breeding value A_w in Robertson and Price decompositions.',
    aliases: ['e_{w}', 'e_w', 'Fitness Breeding-Value Residual', 'Fitness Residual'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration from Formula 6.29 and nearby formulas: e_w is the residual in the decomposition w = A_w + e_w.',
    confidence: 0.93,
  }],
  ['chapter6::formula_6.31a::used::e_{\\overline{{z}}}', {
    concept_name: 'Mean Offspring Trait Residual',
    concept_type: 'quantity_concept',
    definition: 'The residual of mean offspring trait value after removing the component predicted by the parent trait z in the partial-covariance decomposition.',
    aliases: ['e_{\\overline{{z}}}', 'e_overline_z', 'Mean Offspring Trait Residual', 'Offspring Trait Residual'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration from Formula 6.31a: e_overline_z is paired with e_w to express the partial covariance sigma(w, overline z || z).',
    confidence: 0.91,
  }],
  ['chapter6::formula_6.32::defined::R_z', {
    concept_name: 'Trait Response',
    concept_type: 'quantity_concept',
    definition: 'The response to selection in the focal trait z, combining the breeder-equation term with residual partial covariance and transmission bias.',
    aliases: ['R_z', 'Trait Response', 'Response in Trait z'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration from Formula 6.32: R_z is the Price-frame trait response, not a raw symbol node.',
    confidence: 0.95,
  }],
  ['chapter6::formula_6.33c::used::\\mu_{x}', {
    concept_name: 'Regression Variable Mean',
    concept_type: 'quantity_concept',
    definition: 'The mean of the variable being residualized with respect to parent trait z in the partial-covariance regression expression.',
    aliases: ['\\mu_{x}', 'mu_x', 'Regression Variable Mean', 'Mean of Residualized Variable'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration from Formula 6.33c: mu_x centers the variable x before forming the regression residual e_x.',
    confidence: 0.9,
  }],
  ['chapter6::formula_6.38::used::\\overline{{\\delta}}_{i}', {
    concept_name: 'Mean Transmission Deviation',
    concept_type: 'quantity_concept',
    definition: 'The expected mean descendant change for class i, decomposed into average-effect change and the difference between adjusted offspring and ancestor trait values.',
    aliases: ['\\overline{{\\delta}}_{i}', 'overline_delta_i', 'Mean Transmission Deviation', 'Mean Descendant Change'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration from Formula 6.38: overline delta_i is the Price transmission term being decomposed, not a spelled-out symbol artifact.',
    confidence: 0.91,
  }],
  ['appendix1::formula_A1.52::defined::m', {
    concept_name: 'Ornstein-Uhlenbeck Drift Function',
    concept_type: 'operator_or_function',
    definition: 'The deterministic drift function in the Ornstein-Uhlenbeck process, representing a linear restoring force toward the origin.',
    aliases: ['m', 'm(x)', 'Ornstein-Uhlenbeck Drift Function', 'Linear Restoring Drift'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration from Formula A1.52 metadata and local text: m(x) = -ax is the OU drift term, not a mean.',
    confidence: 0.94,
  }],
  ['appendix2::formula_A2.56::defined::\\mu_{x}', {
    concept_name: 'Distribution Mean',
    concept_type: 'quantity_concept',
    definition: 'The mean of a gamma distribution, parameterized by shape alpha and rate beta or equivalently by scale lambda.',
    aliases: ['\\mu_{x}', 'mu_x', 'Distribution Mean', 'Gamma Distribution Mean'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_llm_fix',
    replace_aliases: true,
    review_notes: 'LLM repair accepted after normalization: Formula A2.56 gives the mean of the gamma distribution.',
    confidence: 0.9,
  }],
  ['appendix2::formula_A2.66::defined::\\mu_{x}', {
    concept_name: 'Distribution Mean',
    concept_type: 'quantity_concept',
    definition: 'The mean of an inverse chi-square distribution, expressed in terms of its degrees of freedom.',
    aliases: ['\\mu_{x}', 'mu_x', 'Distribution Mean', 'Inverse Chi-Square Distribution Mean'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_llm_fix',
    replace_aliases: true,
    review_notes: 'LLM repair accepted after normalization: Formula A2.66 gives the mean of the inverse chi-square distribution.',
    confidence: 0.9,
  }],
  ['chapter13::formula_13.10a::used::\\mu_{y}', {
    concept_name: 'Offspring Trait Mean',
    concept_type: 'quantity_concept',
    definition: 'The population mean of the offspring trait y used as the centering value in the parent-offspring regression expression.',
    aliases: ['\\mu_{y}', 'mu_y', 'Offspring Trait Mean'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_llm_fix',
    replace_aliases: true,
    review_notes: 'Rule calibration from Formula 13.10a: y_o is the offspring trait, so mu_y is its population mean.',
    confidence: 0.92,
  }],
  ['chapter15::formula_15.34a::defined::m', {
    concept_name: 'Maternal Effect Coefficient',
    concept_type: 'quantity_concept',
    definition: 'The parameter controlling how maternal-effect contribution is diluted or retained in Falconer-style selection-response dynamics.',
    aliases: ['m', 'Maternal Effect Coefficient', 'Falconer Dilution Parameter'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_llm_fix',
    review_notes: 'LLM repair accepted with local subsection evidence: Formula 15.34a constrains m in Falconer’s dilution model.',
    confidence: 0.9,
  }],
  ['chapter24::formula_24.25b::defined::f', {
    concept_name: 'Allele-Frequency Moment Function',
    concept_type: 'operator_or_function',
    definition: 'A function of allele frequencies, such as a moment of the allelic distribution, whose short-term change is approximated by a Taylor series.',
    aliases: ['f', 'Allele-Frequency Moment Function'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_llm_fix',
    review_notes: 'LLM repair accepted after normalization: local text defines f as a function of allele frequencies, such as an allelic-distribution moment.',
    confidence: 0.92,
  }],
  ['chapter29::formula_29.18a::defined::\\mu', {
    concept_name: 'Phenotypic Trait Mean',
    concept_type: 'quantity_concept',
    definition: 'The mean of the phenotypic trait z used to center higher-order phenotypic moments in the quadratic-selection expression.',
    aliases: ['\\mu', 'mu', 'Phenotypic Trait Mean'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_llm_fix',
    replace_aliases: true,
    review_notes: 'LLM repair accepted after normalization: Formula 29.18a uses mu to center phenotypic trait z.',
    confidence: 0.9,
  }],
  ['chapter29::formula_29.40b::defined::\\mu_{y}', {
    concept_name: 'Negative-Binomial Distribution Mean',
    concept_type: 'quantity_concept',
    definition: 'The mean of a negative-binomial random variable y under the generalized-linear-model fitness-component example.',
    aliases: ['\\mu_{y}', 'mu_y', 'Negative-Binomial Distribution Mean'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_llm_fix',
    replace_aliases: true,
    review_notes: 'Rule calibration from Formula 29.40b: the local text states that y follows a negative-binomial distribution and the formula gives its mean and variance.',
    confidence: 0.94,
  }],
  ['appendix2::formula_A2.63::defined::\\mu_{x}', {
    concept_name: 'Distribution Mean',
    concept_type: 'quantity_concept',
    definition: 'The mean of the inverse-gamma distribution, finite only when the shape parameter is large enough.',
    aliases: ['\\mu_{x}', 'mu_x', 'Distribution Mean', 'Inverse-Gamma Distribution Mean'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    replace_aliases: true,
    review_notes: 'Rule calibration: the formula gives the mean of the local probability distribution; use a stable symbol-level name across this distribution subsection.',
    confidence: 0.92,
  }],
  ['chapter8::formula_8.3b::defined::f_{s}', {
    concept_name: 'Hitchhiking Reduction Factor',
    concept_type: 'quantity_concept',
    definition: 'The sweep-linked reduction factor describing how recombination and selection scale the linked neutral allele-frequency change during hitchhiking.',
    aliases: ['f_{s}', 'f_s', 'Hitchhiking Reduction Factor'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration: Equations 8.3b-d use f_s as the hitchhiking scaling factor, not separate unrelated concepts.',
    confidence: 0.9,
  }],
  ['chapter8::formula_8.3d::defined::f_{s}', {
    concept_name: 'Hitchhiking Reduction Factor',
    concept_type: 'quantity_concept',
    definition: 'The sweep-linked reduction factor approximated under the Maynard Smith-Haigh hitchhiking expression.',
    aliases: ['f_{s}', 'f_s', 'Hitchhiking Reduction Factor'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration: keep the approximation of f_s aligned with its defining hitchhiking factor.',
    confidence: 0.9,
  }],
  ['chapter8::formula_8.3f::defined::f_{s}', {
    concept_name: 'Hitchhiking Reduction Factor',
    concept_type: 'quantity_concept',
    definition: 'The sweep-linked reduction factor under dominance-adjusted selective hitchhiking.',
    aliases: ['f_{s}', 'f_s', 'Hitchhiking Reduction Factor'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration: local text treats this as the same f_s approximation under modified dominance assumptions.',
    confidence: 0.88,
  }],
  ['chapter8::formula_8.3g::defined::f_{s}', {
    concept_name: 'Hitchhiking Reduction Factor',
    concept_type: 'quantity_concept',
    definition: 'The sweep-linked reduction factor evaluated for a new favorable mutation starting at frequency 1/(2N).',
    aliases: ['f_{s}', 'f_s', 'Hitchhiking Reduction Factor'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration: keep f_s consistent across the selective hitchhiking approximations in Equation 8.3.',
    confidence: 0.88,
  }],
  ['chapter9::formula_9.19a::defined::x', {
    concept_name: 'Allele Frequency',
    concept_type: 'quantity_concept',
    definition: 'The allele frequency modeled through a normal approximation under drift.',
    aliases: ['x', 'Allele Frequency'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration: local text states x is the expected frequency of an allele at generation t.',
    confidence: 0.9,
  }],
  ['chapter9::formula_9.19b::defined::x', {
    concept_name: 'Allele Frequency',
    concept_type: 'quantity_concept',
    definition: 'The allele frequency in the candidate population under the pure-drift comparison model.',
    aliases: ['x', 'Allele Frequency', 'Candidate Allele Frequency'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration: preserve one symbol-level concept name for x in the CLRT-GOF subsection.',
    confidence: 0.9,
  }],
  ['chapter9::formula_9.20::defined::x', {
    concept_name: 'Allele Frequency',
    concept_type: 'quantity_concept',
    definition: 'The allele frequency under the selective-sweep mixture model used by the CLRT-GOF test.',
    aliases: ['x', 'Allele Frequency'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration: formula 9.20 continues the same local allele-frequency variable x under the sweep alternative.',
    confidence: 0.9,
  }],
  ['chapter12::formula_12.20d::defined::h_{m}^{2}', {
    concept_name: 'Mutational Heritability',
    concept_type: 'quantity_concept',
    definition: 'The mutational heritability bounded by the Brownian-motion divergence test.',
    aliases: ['h_{m}^{2}', 'h_m^2', 'Mutational Heritability'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration: the following test equations interpret h_m^2 as mutational heritability.',
    confidence: 0.9,
  }],
  ['chapter12::formula_12.20e::defined::h_{m}^{2}', {
    concept_name: 'Mutational Heritability',
    concept_type: 'quantity_concept',
    definition: 'The mutational heritability interval implied by the Brownian-motion divergence test.',
    aliases: ['h_{m}^{2}', 'h_m^2', 'Mutational Heritability'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration: keep h_m^2 aligned with the mutational-heritability interpretation used in the rejection conditions.',
    confidence: 0.9,
  }],
  ['chapter15::formula_15.27a::defined::m', {
    concept_name: 'Maternal Effect Coefficient',
    concept_type: 'quantity_concept',
    definition: 'The maternal-effect coefficient whose sign and magnitude determine whether the short-term response can reverse.',
    aliases: ['m', 'Maternal Effect Coefficient'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration: the Falconer dilution subsection uses m for the maternal-effect coefficient.',
    confidence: 0.9,
  }],
  ['chapter15::formula_15.27b::defined::m', {
    concept_name: 'Maternal Effect Coefficient',
    concept_type: 'quantity_concept',
    definition: 'The maternal-effect coefficient constrained by the female-selection reversed-response condition.',
    aliases: ['m', 'Maternal Effect Coefficient'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration: align m with the local maternal-effect coefficient instead of a generic mean.',
    confidence: 0.9,
  }],
  ['chapter15::formula_15.34b::defined::m', {
    concept_name: 'Maternal Effect Coefficient',
    concept_type: 'quantity_concept',
    definition: 'The maternal-effect coefficient threshold above which response continues after selection is relaxed.',
    aliases: ['m', 'Maternal Effect Coefficient'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration: local text explicitly refers to maternal effects when introducing this bound on m.',
    confidence: 0.9,
  }],
  ['chapter25::formula_25.1a::defined::m', {
    concept_name: 'Mean Genotypic Value',
    concept_type: 'quantity_concept',
    definition: 'The mean genotypic value contributed by a single locus as a function of allele frequency.',
    aliases: ['m', 'm(p)', 'Mean Genotypic Value'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration: m(p) is the single-locus mean contribution function in Equation 25.1.',
    confidence: 0.92,
  }],
  ['chapter25::formula_25.1b::defined::m', {
    concept_name: 'Mean Genotypic Value',
    concept_type: 'quantity_concept',
    definition: 'The change in mean genotypic value from the starting allele frequency to fixation.',
    aliases: ['m', 'm(p)', 'Mean Genotypic Value'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration: keep differences of m(p) under the same mean-genotypic-value concept.',
    confidence: 0.9,
  }],
  ['chapter25::formula_25.1d::defined::m', {
    concept_name: 'Mean Genotypic Value',
    concept_type: 'quantity_concept',
    definition: 'The change in mean genotypic value between the estimated and starting allele frequencies.',
    aliases: ['m', 'm(p)', 'Mean Genotypic Value'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration: m remains the same mean-genotypic-value function when evaluated at different allele frequencies.',
    confidence: 0.9,
  }],
  ['chapter25::formula_25.1e::defined::m', {
    concept_name: 'Mean Genotypic Value',
    concept_type: 'quantity_concept',
    definition: 'The fraction of the total mean genotypic contribution reached at allele frequency p_beta.',
    aliases: ['m', 'm(p)', 'Mean Genotypic Value'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    review_notes: 'Rule calibration: the expression still compares evaluations of the same m(p) function.',
    confidence: 0.9,
  }],
  ['chapter4::formula_4.4b::defined::b_{n}', {
    concept_name: 'Reciprocal-Squares Harmonic Sum',
    concept_type: 'quantity_concept',
    definition: 'The finite sum of reciprocal squares over sample indices, used as a correction term in neutral segregating-sites calculations.',
    aliases: ['b_{n}', 'b_n', 'Reciprocal-Squares Harmonic Sum'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_llm_fix',
    review_notes: 'LLM repair accepted after removing formula text: Formula 4.4b defines b_n as a reciprocal-square sum for segregating-sites statistics.',
    confidence: 0.92,
  }],
  ['chapter8::formula_8.3g::defined::f_{s}', {
    concept_name: 'Hitchhiking Event Strength',
    concept_type: 'quantity_concept',
    definition: 'The critical measure of selective-sweep strength, giving the fraction of initial marker association that persists when the selected allele fixes.',
    aliases: ['f_{s}', 'f_s', 'Hitchhiking Event Strength', 'Sweep Strength'],
    review_status: 'edited',
    review_flags: ['llm_validated'],
    reviewed_by: 'auto_rule_fix',
    replace_aliases: true,
    review_notes: 'Rule calibration from Chapter 8 local definition: Formula 8.1d names f_s as the critical measure of hitchhiking-event strength, and Formula 8.3g is a later approximation for the same quantity.',
    confidence: 0.95,
  }],
  ['chapter2::formula_2.42::defined::F_{ST}', {
    concept_name: 'Fixation Index',
    concept_type: 'quantity_concept',
    definition: 'A standardized measure of population differentiation among subpopulations, expressed as the among-population allele-frequency variance relative to total expected heterozygosity.',
    definition_zh: '衡量亚群体间等位基因频率分化程度的标准化指标，用群体间频率方差相对于总体期望杂合度来表示。',
    aliases: ['F_{ST}', 'FST', 'Fixation Index', 'Wright Fixation Index'],
    replace_aliases: true,
    replace_review_notes: true,
    confidence: 0.96,
    review_notes: 'Rule calibration: F_ST is Wright’s fixation index, not a parsed phrase from metapopulation text.',
  }],
  ['chapter2::formula_2.42::used::\\sigma^{2}(p)', {
    concept_name: 'Among-Deme Allele-Frequency Variance',
    concept_type: 'quantity_concept',
    definition: 'The variance in allele frequency among demes, used as the among-population variance component in FST.',
    definition_zh: '亚群体之间等位基因频率的方差，是 FST 中表示群体间分化的方差组成部分。',
    aliases: ['\\sigma^{2}(p)', 'sigma^2(p)', 'among-deme allele-frequency variance'],
    replace_aliases: true,
    replace_review_notes: true,
    confidence: 0.94,
    review_notes: 'Rule calibration: Formula 2.42 uses sigma^2(p) as the among-deme allele-frequency variance in the FST numerator, not a parsed phrase from the surrounding text.',
  }],
  ['chapter19::formula_19.2a::defined::\\mathbf{V}', {
    concept_name: 'Observation Covariance Matrix',
    concept_type: 'quantity_concept',
    definition: 'The covariance matrix of the observation vector in the mixed model, combining additive genetic and residual variance components.',
    aliases: ['\\mathbf{V}', 'V', 'Observation Covariance Matrix', 'Covariance Matrix'],
    replace_aliases: true,
    replace_review_notes: true,
    confidence: 0.95,
    review_notes: 'Rule calibration: Formula 19.2a defines V = Cov(y) for the mixed-model observation vector.',
  }],
  ['chapter19::formula_19.3d::defined::\\mathbf{M}', {
    concept_name: 'Projection Matrix',
    concept_type: 'math_concept',
    definition: 'The projection matrix used to remove the fixed-effect design space in Henderson-style mixed-model calculations.',
    aliases: ['\\mathbf{M}', 'M', 'Projection Matrix'],
    replace_aliases: true,
    replace_review_notes: true,
    confidence: 0.94,
    review_notes: 'Rule calibration: Formula 19.3d defines the projection matrix M = I - X(X^T X)^-1 X^T.',
  }],
  ['chapter8::formula_8.8b::defined::\\frac{H_{h}}{H_{0}}', {
    concept_name: 'Relative Sweep-Linked Heterozygosity',
    concept_type: 'quantity_concept',
    definition: 'The heterozygosity remaining after a sweep, expressed relative to the baseline heterozygosity H0.',
    definition_zh: '选择扫荡后保留下来的杂合度相对基准杂合度的比例，用来直接读出遗传多样性还剩多少。',
    aliases: ['\\frac{H_{h}}{H_{0}}', 'H_h/H_0', 'Relative Sweep-Linked Heterozygosity'],
    review_notes: 'Curated from Formula 8.8b: H_h/H_0 is approximated as 1 - p(0)^(2c/s).',
  }],
  ['chapter8::formula_8.8e::defined::\\eta', {
    concept_name: 'Recessive Sweep Recombination Scale',
    concept_type: 'quantity_concept',
    definition: 'A dimensionless recombination scale for a fully recessive sweep, eta = c sqrt(4Ne/s).',
    definition_zh: '完全隐性选择扫荡中的重组尺度参数，η = c√(4Ne/s)，用来衡量中性位点通过重组逃离扫荡影响的机会。',
    aliases: ['\\eta', 'eta', 'Recessive Sweep Recombination Scale'],
    review_notes: 'Curated from Formula 8.8e context: Ewing et al. show H_h/H_0 ≃ eta/(1+eta) where eta=c sqrt(4Ne/s).',
  }],
  ['chapter8::formula_8.23::defined::\\chi', {
    concept_name: 'Characteristic Dispersal Length',
    concept_type: 'quantity_concept',
    definition: 'The characteristic dispersal length in a geographically structured sweep model.',
    definition_zh: '地理结构软扫荡模型中的特征扩散长度，用来刻画有利突变扩散时影响范围的空间尺度。',
    aliases: ['\\chi', 'chi', 'Characteristic Dispersal Length'],
    review_notes: 'Curated from Formula 8.23 context: Ralph and Coop identify chi as the key characteristic dispersal length.',
  }],
  ['chapter30::formula_30.33c::defined::\\boldsymbol{\\eta}', {
    concept_name: 'Extended Selection Gradient Vector',
    concept_type: 'quantity_concept',
    definition: "Morrissey's extended selection gradient vector, computed from the total-effect matrix and path-analysis selection gradients.",
    definition_zh: 'Morrissey 路径分析中的扩展选择梯度向量，把直接路径系数通过总效应矩阵转换为包含间接路径的选择梯度。',
    aliases: ['\\boldsymbol{\\eta}', '\\eta', 'eta', 'Extended Selection Gradient Vector'],
    review_notes: 'Curated from Formula 30.33c subsection title and equation eta = Phi beta_pa.',
  }],
  ['chapter30::formula_30.33c::used::\\Phi', {
    concept_name: 'Total-Effect Matrix',
    concept_type: 'math_concept',
    definition: 'A matrix that converts direct path-analysis coefficients into total effects, including indirect pathways.',
    definition_zh: '总效应矩阵，把直接路径系数转换成包含间接路径在内的总效应。',
    aliases: ['\\Phi', 'Phi', 'Total-Effect Matrix'],
    review_notes: 'Curated from Formula 30.33c: eta = Phi beta_pa.',
  }],
  ['chapter30::formula_30.33c::used::\\beta', {
    concept_name: 'Path-Analysis Selection Gradient Vector',
    concept_type: 'quantity_concept',
    definition: 'A vector of direct selection gradients estimated in the path-analysis model.',
    definition_zh: '路径分析模型中的直接选择梯度向量，表示各条直接路径上的选择效应。',
    aliases: ['\\beta_{pa}', '\\beta', 'Path-Analysis Selection Gradient Vector'],
    review_notes: 'Curated from Formula 30.33c: beta_pa is transformed by Phi.',
  }],
  ['chapter18::formula_18.23a::defined::\\overline{z}_{s,t}', {
    concept_name: 'Selected Population Mean Trait Value',
    concept_type: 'quantity_concept',
    definition: 'The observed mean trait value for the selected population at time t.',
    definition_zh: '第 t 个时间点中，选择组群体的观测平均性状值。',
    aliases: ['\\overline{z}_{s,t}', 'selected population mean', 'Selected Population Mean Trait Value'],
    review_notes: 'Curated from the local text: selected (s) and control (c) population means are decomposed in Equations 18.23a-b.',
  }],
  ['chapter18::formula_18.23a::used::s', {
    concept_name: 'Selected Population',
    concept_type: 'domain_concept',
    definition: 'The population or line subjected to selection.',
    definition_zh: '受到选择处理的群体或品系。',
    aliases: ['s', 'selected', 'Selected Population'],
    review_notes: 'Curated from the local text: selected (s) and control (c) population.',
  }],
  ['chapter18::formula_18.23a::used::t', {
    concept_name: 'Time',
    concept_type: 'quantity_concept',
    definition: 'A quantity indexing the stage, generation, or interval of the process.',
    definition_zh: '表示过程所处阶段、世代或时间间隔的量。',
    aliases: ['t', 'Time'],
    review_notes: 'Curated for the selected population mean at time t.',
  }],
  ['chapter18::formula_18.23b::defined::\\overline{z}_{c,t}', {
    concept_name: 'Control Population Mean Trait Value',
    concept_type: 'quantity_concept',
    definition: 'The observed mean trait value for the control population at time t.',
    definition_zh: '第 t 个时间点中，对照组群体的观测平均性状值。',
    aliases: ['\\overline{z}_{c,t}', 'control population mean', 'Control Population Mean Trait Value'],
    review_notes: 'Curated from the local text: selected (s) and control (c) population means are decomposed in Equations 18.23a-b.',
  }],
  ['chapter18::formula_18.23b::used::c', {
    concept_name: 'Control Population',
    concept_type: 'domain_concept',
    definition: 'The control population or line used as the comparison baseline.',
    definition_zh: '作为比较基线的对照组群体或对照品系。',
    aliases: ['c', 'control', 'Control Population'],
    review_notes: 'Curated from the local text: selected (s) and control (c) population.',
  }],
  ['chapter18::formula_18.23b::used::t', {
    concept_name: 'Time',
    concept_type: 'quantity_concept',
    definition: 'A quantity indexing the stage, generation, or interval of the process.',
    definition_zh: '表示过程所处阶段、世代或时间间隔的量。',
    aliases: ['t', 'Time'],
    review_notes: 'Curated for the control population mean at time t.',
  }],
  ['chapter18::formula_18.25b::defined::R_{C}', {
    concept_name: 'Cumulative Response',
    concept_type: 'quantity_concept',
    definition: 'The cumulative response, computed as the selected population mean minus the control population mean at time t.',
    definition_zh: '第 t 个时间点中，选择组平均性状值与对照组平均性状值之差表示的累积响应。',
    aliases: ['R_{C}', 'R_C', 'cumulative response', 'Cumulative Response'],
    review_notes: 'Curated from the local text: R_C(t) is introduced in the section describing cumulative responses and differentials.',
  }],
  ['chapter18::formula_18.25b::used::c', {
    concept_name: 'Control Population',
    concept_type: 'domain_concept',
    definition: 'The control population or line used as the comparison baseline.',
    definition_zh: '作为比较基线的对照组群体或对照品系。',
    aliases: ['c', 'control', 'Control Population'],
    review_notes: 'Curated from the local text: selected (s) and control (c) population.',
  }],
  ['chapter18::formula_18.25b::used::s', {
    concept_name: 'Selected Population',
    concept_type: 'domain_concept',
    definition: 'The population or line subjected to selection.',
    definition_zh: '受到选择处理的群体或品系。',
    aliases: ['s', 'selected', 'Selected Population'],
    review_notes: 'Curated from the local text: selected (s) and control (c) population.',
  }],
  ['chapter18::formula_18.25b::used::t', {
    concept_name: 'Time',
    concept_type: 'quantity_concept',
    definition: 'A quantity indexing the stage, generation, or interval of the process.',
    definition_zh: '表示过程所处阶段、世代或时间间隔的量。',
    aliases: ['t', 'Time'],
    review_notes: 'Curated for the cumulative response expression R_C(t).',
  }],
  ['chapter18::formula_18.25c::defined::S_{t}', {
    concept_name: 'Selection Differential',
    concept_type: 'quantity_concept',
    definition: 'The selection differential for time t.',
    definition_zh: '第 t 个时间点对应的选择差。',
    aliases: ['S_{t}', 'selection differential', 'Selection Differential'],
    review_notes: 'Curated from the local text: responses and differentials are estimated together in Equations 18.25b-d.',
  }],
  ['chapter18::formula_18.25d::defined::S_{C}', {
    concept_name: 'Cumulative Selection Differential',
    concept_type: 'quantity_concept',
    definition: 'The cumulative selection differential up to time t.',
    definition_zh: '截至第 t 个时间点累积得到的选择差。',
    aliases: ['S_{C}', 'S_C', 'cumulative selection differential', 'Cumulative Selection Differential'],
    review_notes: 'Curated from the local text: S_C(t) is the cumulative selection differential.',
  }],
  ['appendix5::formula_A5.4::defined::\\theta', {
    concept_name: 'Vector Angle',
    concept_type: 'math_concept',
    definition: 'The angle between two vectors, computed from their normalized dot product.',
    aliases: ['\\theta', 'theta', 'Vector Angle'],
    review_notes: 'Curated for public appendix coverage: the formula defines the angle between two vectors from their dot product.',
  }],
  ['appendix5::formula_A5.15::defined::\\mathbf{I}', {
    concept_name: 'Identity Matrix',
    concept_type: 'math_concept',
    definition: 'A matrix with ones on the diagonal and zeros elsewhere.',
    aliases: ['\\mathbf{I}', 'I', 'Identity Matrix'],
    review_notes: 'Curated for public appendix coverage: the identity matrix appears in the characteristic matrix expression.',
  }],
  ['appendix5::formula_A5.48::defined::\\phi', {
    concept_name: 'Multivariate Normal Density',
    concept_type: 'math_concept',
    definition: 'A probability density for a normally distributed vector, parameterized by a mean vector and covariance matrix.',
    aliases: ['\\phi', 'phi', 'Multivariate Normal Density', 'Probability Density'],
    review_notes: 'Curated for public appendix coverage: the formula gives the multivariate normal density.',
  }],
  ['appendix5::formula_A5.56::defined::\\lambda_{i}', {
    concept_name: 'Eigenvalue',
    concept_type: 'math_concept',
    definition: 'A scalar value associated with a matrix transformation or covariance structure.',
    aliases: ['\\lambda_{i}', 'lambda_i', 'Eigenvalue'],
    review_notes: 'Curated for public appendix coverage: the formula expresses variance share through covariance-matrix eigenvalues.',
  }],
  ['appendix6::formula_A6.2::defined::\\varphi', {
    concept_name: 'Multivariate Normal Density',
    concept_type: 'math_concept',
    definition: 'A probability density for a normally distributed vector, parameterized by a mean vector and covariance matrix.',
    aliases: ['\\varphi', 'varphi', 'Multivariate Normal Density', 'Probability Density'],
    review_notes: 'Curated for public appendix coverage: the formula differentiates the multivariate normal density.',
  }],
  ['appendix6::formula_A6.10::defined::\\widehat{\\boldsymbol{\\beta}}', {
    concept_name: 'Fixed-Effect Estimator Vector',
    concept_type: 'quantity_concept',
    definition: 'A vector of estimated fixed-effect coefficients used in mixed-model equations.',
    aliases: ['\\widehat{\\boldsymbol{\\beta}}', 'beta hat', 'Fixed-Effect Estimator Vector'],
    review_notes: 'Curated for public appendix coverage: the formula solves for the estimated fixed-effect coefficient vector.',
  }],
  ['appendix6::formula_A6.14::defined::g', {
    concept_name: 'Lagrangian Objective',
    concept_type: 'math_concept',
    definition: 'An augmented objective function used to optimize a function subject to a constraint.',
    aliases: ['g', 'Lagrangian Objective'],
    review_notes: 'Curated for public appendix coverage: the formula constructs the Lagrangian objective for constrained optimization.',
  }],
  ['appendix6::formula_A6.15::defined::\\lambda', {
    concept_name: 'Lagrange Multiplier',
    concept_type: 'math_concept',
    definition: 'A parameter introduced to optimize a function while enforcing a constraint.',
    aliases: ['\\lambda', 'lambda', 'Lagrange Multiplier'],
    review_notes: 'Curated for public appendix coverage: the formula uses lambda as the multiplier in the constrained-gradient condition.',
  }],
]);

export const PRODUCT_GENERIC_CONCEPT_NAMES = new Set([
  'chi',
  'coefficient',
  'count',
  'distance',
  'ell',
  'eta',
  'expression',
  'fact',
  'function',
  'index',
  'mean',
  'model quantity',
  'approach used',
  'offspring',
  'rate',
  'ratio of',
  'same logic',
  'there',
  'time index',
  'indexed quantity',
  'class quantity',
  'value',
  'values',
  'variable',
]);

export const COMMON_SYMBOL_NAMES = new Map([
  ['N', 'Population Size'],
  ['n', 'Count'],
  ['i', 'Index'],
  ['j', 'Index'],
  ['k', 'Index'],
  ['t', 'Time'],
  ['p', 'Probability'],
  ['q', 'Frequency'],
  ['w', 'Fitness'],
  ['W', 'Absolute Fitness'],
  ['z', 'Trait Value'],
  ['x', 'Variable'],
  ['y', 'Response Variable'],
  ['S', 'Selection Differential'],
  ['R', 'Response'],
  ['V', 'Variance'],
  ['C', 'Cost'],
  ['B', 'Benefit'],
  ['E', 'Expectation'],
  ['Cov', 'Covariance'],
  ['Var', 'Variance'],
  ['Pr', 'Probability'],
  ['P', 'Probability'],
  ['L', 'Likelihood'],
  ['a', 'Coefficient'],
  ['b', 'Coefficient'],
  ['d', 'Distance'],
  ['f', 'Function'],
  ['h', 'Function'],
  ['m', 'Mean'],
  ['o', 'Order Term'],
  ['r', 'Rate'],
  ['s', 'Selection Coefficient'],
  ['u', 'Mutation Rate'],
  ['v', 'Variance Function'],
  ['T', 'Time'],
  ['I', 'Information'],
  ['ln', 'Natural Logarithm'],
  ['\\ln', 'Natural Logarithm'],
  ['exp', 'Exponential Function'],
  ['\\exp', 'Exponential Function'],
  ['B_{0}', 'Bayes Factor'],
  ['I_{f}', 'Fixation Integral'],
  ['\\varphi', 'Probability Density'],
  ['\\phi', 'Probability Density'],
  ['\\pi', 'Stationary Distribution'],
  ['\\Gamma', 'Gamma Function'],
  ['\\nu', 'Degrees of Freedom'],
  ['\\theta', 'Parameter'],
  ['\\widehat{\\theta}', 'Estimator'],
  ['\\Theta', 'Parameter Vector'],
  ['\\boldsymbol{\\theta}', 'Parameter Vector'],
  ['\\widehat{\\boldsymbol{\\theta}}', 'Estimator Vector'],
  ['\\boldsymbol{\\Theta}', 'Parameter Vector'],
  ['\\mathbf{x}', 'Data Vector'],
  ['\\mathbf{I}', 'Identity Matrix'],
  ['\\mathbf{V}', 'Covariance Matrix'],
  ['\\mathbf{W}', 'Wishart Matrix'],
  ['\\mathrm{P}', 'Probability'],
  ['\\mathrm{V}', 'Variance'],
  ['\\mathrm{r}', 'Rate'],
  ['\\mathrm{a}', 'Acceptance Rate'],
  ['NI', 'Neutrality Index'],
  ['NI_{TG}', 'Tarone-Greenland Neutrality Index'],
  ['DoS', 'Direction of Selection Statistic'],
]);

export const SUBSCRIPT_SYMBOL_NAMES = [
  { pattern: /^D_\{?ai\}?$/i, name: 'Replacement-Site Divergence per Gene', type: 'quantity_concept' },
  { pattern: /^D_\{?si\}?$/i, name: 'Silent-Site Divergence per Gene', type: 'quantity_concept' },
  { pattern: /^P_\{?ai\}?$/i, name: 'Replacement-Site Polymorphism per Gene', type: 'quantity_concept' },
  { pattern: /^P_\{?si\}?$/i, name: 'Silent-Site Polymorphism per Gene', type: 'quantity_concept' },
  { pattern: /^D_\{?a\}?$/i, name: 'Replacement-Site Divergence', type: 'quantity_concept' },
  { pattern: /^D_\{?s\}?$/i, name: 'Silent-Site Divergence', type: 'quantity_concept' },
  { pattern: /^P_\{?a\}?$/i, name: 'Replacement-Site Polymorphism', type: 'quantity_concept' },
  { pattern: /^P_\{?s\}?$/i, name: 'Silent-Site Polymorphism', type: 'quantity_concept' },
  { pattern: /^S_\{?a\}?$/i, name: 'Replacement-Site Segregating Sites', type: 'quantity_concept' },
  { pattern: /^S_\{?s\}?$/i, name: 'Silent-Site Segregating Sites', type: 'quantity_concept' },
  { pattern: /^\\mu_\{?a\}?$/i, name: 'Replacement-Site Mutation Rate', type: 'quantity_concept' },
  { pattern: /^\\mu_\{?s\}?$/i, name: 'Silent-Site Mutation Rate', type: 'quantity_concept' },
  { pattern: /^\\theta_\{?a\}?$/i, name: 'Replacement-Site Theta', type: 'quantity_concept' },
  { pattern: /^\\theta_\{?s\}?$/i, name: 'Silent-Site Theta', type: 'quantity_concept' },
  { pattern: /^n_\{?a\}?$/i, name: 'Replacement-Site Count', type: 'quantity_concept' },
  { pattern: /^n_\{?s\}?$/i, name: 'Silent-Site Count', type: 'quantity_concept' },
  { pattern: /^D_\{?a,n\}?$/i, name: 'Neutral Replacement Substitutions', type: 'quantity_concept' },
  { pattern: /^\\eta_\{?a\}?$/i, name: 'Adaptive Replacement Substitutions', type: 'quantity_concept' },
  { pattern: /^\\widehat\{\\eta\}_\{?a\}?$/i, name: 'Estimated Adaptive Replacement Substitutions', type: 'quantity_concept' },
  { pattern: /^\\(?:overline|bar)\{?z\}?$/i, name: 'Mean Trait Value', type: 'quantity_concept' },
  { pattern: /^\\(?:overline|bar)\{?[Ww]\}?$/i, name: 'Mean Fitness', type: 'quantity_concept' },
  { pattern: /^A$/i, name: 'Additive Genetic Value', type: 'quantity_concept' },
  { pattern: /^A_\{?T(?:,n)?\}?$/i, name: 'Total Additive Genetic Value', type: 'quantity_concept' },
  { pattern: /^A_\{?incf\}?$/i, name: 'Inclusive-Fitness Breeding Value', type: 'quantity_concept' },
  { pattern: /^A_\{?w\}?$/i, name: 'Fitness Breeding Value', type: 'quantity_concept' },
  { pattern: /^A_\{?z\}?$/i, name: 'Trait Breeding Value', type: 'quantity_concept' },
  { pattern: /^\\overline\{A\}_\{?z\}?$/i, name: 'Mean Trait Breeding Value', type: 'quantity_concept' },
  { pattern: /^\\widehat\{A\}_\{?.+\}?$/i, name: 'Estimated Relationship Matrix', type: 'quantity_concept' },
  { pattern: /^A_\{?.+\}?$/i, name: 'Additive Genetic Component', type: 'quantity_concept' },
  { pattern: /^A\^\{?.+\}?$/i, name: 'Additive Matrix Exponentiation', type: 'math_concept' },
  { pattern: /^\\widehat\{?\\boldsymbol\{?.+\}?\}?$/i, name: 'Estimator Vector', type: 'quantity_concept' },
  { pattern: /^\\boldsymbol\{?.+\}?$/i, name: 'Parameter Vector', type: 'quantity_concept' },
  { pattern: /^\\mathbf\{?I\}?$/i, name: 'Identity Matrix', type: 'math_concept' },
  { pattern: /^\\mathbf\{?.+\}?$/i, name: 'Vector or Matrix Quantity', type: 'math_concept' },
  { pattern: /^P_\{?ij\}?$/i, name: 'Wright-Fisher Transition Probability', type: 'quantity_concept' },
  { pattern: /^P_\{?.+\}?$/i, name: 'Probability', type: 'quantity_concept' },
  { pattern: /^s_\{?.+\}?$/i, name: 'Class Selection Coefficient', type: 'quantity_concept' },
  { pattern: /^q_\{?i\}?$/i, name: 'Class Frequency', type: 'quantity_concept' },
  { pattern: /^z_\{?i\}?$/i, name: 'Class Trait Value', type: 'quantity_concept' },
  { pattern: /^w_\{?i\}?$/i, name: 'Class Fitness', type: 'quantity_concept' },
  { pattern: /^x_\{?i\}?$/i, name: 'State Probability', type: 'quantity_concept' },
  { pattern: /^f_\{?t\}?$/i, name: 'Inbreeding Coefficient', type: 'quantity_concept' },
  { pattern: /^H_\{?t\}?$/i, name: 'Heterozygosity', type: 'quantity_concept' },
  { pattern: /^\\lambda_\{?.+\}?$/i, name: 'Eigenvalue', type: 'math_concept' },
  { pattern: /^\\mu_\{?z\}?$/i, name: 'Mean Trait Value', type: 'quantity_concept' },
  { pattern: /^\\mu_\{?.+\}?$/i, name: 'Mean', type: 'quantity_concept' },
  { pattern: /^c_\{?0\}?$/i, name: 'Baseline Recombination Rate', type: 'quantity_concept' },
  { pattern: /^p\(0\)$/i, name: 'Initial Allele Frequency', type: 'quantity_concept' },
  { pattern: /^p_\{?.+\}?$/i, name: 'Probability', type: 'quantity_concept' },
  { pattern: /^\\sigma\^\{?2\}?\(A_\{?d\}?\)$/i, name: 'Direct Additive Genetic Variance', type: 'quantity_concept' },
  { pattern: /^\\sigma\^\{?2\}?\(A_\{?s\}?\)$/i, name: 'Associative Additive Genetic Variance', type: 'quantity_concept' },
  { pattern: /^\\sigma\^\{?2\}?\(A_\{?T\}?\)$/i, name: 'Total Breeding Value Variance', type: 'quantity_concept' },
  { pattern: /^\\sigma\^\{?2\}?\(A\)$/i, name: 'Additive Genetic Variance', type: 'quantity_concept' },
  { pattern: /^\\sigma_\{?A\}?\^\{?2\}?\((?:t|0)\)$/i, name: 'Additive Genetic Variance', type: 'quantity_concept' },
  { pattern: /^\\sigma\^\{?2\}?\(z\)$/i, name: 'Trait Variance', type: 'quantity_concept' },
  { pattern: /^\\sigma\^\{?2\}?\(e\)$/i, name: 'Environmental Variance', type: 'quantity_concept' },
  { pattern: /^\\sigma_\{?A\}?\^\{?2\}?$/i, name: 'Additive Genetic Variance', type: 'quantity_concept' },
  { pattern: /^\\sigma_\{?B\}?\^\{?2\}?$/i, name: 'Among-Block Variance', type: 'quantity_concept' },
  { pattern: /^\\sigma_\{?G\}?\^\{?2\}?$/i, name: 'Genetic Variance', type: 'quantity_concept' },
  { pattern: /^\\sigma_\{?e\}?\^\{?2\}?$/i, name: 'Within-Block Environmental Variance', type: 'quantity_concept' },
  { pattern: /^\\sigma_\{?z\}?\^\{?2\}?$/i, name: 'Trait Variance', type: 'quantity_concept' },
  { pattern: /^\\sigma(?:_\{?.+\}?)?\^\{?2\}?$/i, name: 'Variance', type: 'quantity_concept' },
  { pattern: /^\\omega(?:\^\{?2\}?)?$/i, name: 'Fitness Width', type: 'quantity_concept' },
  { pattern: /^\\Theta$/, name: 'Parameter Vector', type: 'quantity_concept' },
  { pattern: /^\\theta$/, name: 'Optimal Trait Value', type: 'quantity_concept' },
  { pattern: /^V_\{?s\}?$/i, name: 'Strength of Stabilizing Selection', type: 'quantity_concept' },
  { pattern: /^z\^\{\*\}$/i, name: 'Optimal Trait Value', type: 'quantity_concept' },
  { pattern: /^\\widehat\{?I\}?$/i, name: 'Monte Carlo Estimate', type: 'quantity_concept' },
  { pattern: /^\\widehat\{?h\}?$/i, name: 'Estimated Function', type: 'quantity_concept' },
  { pattern: /^h_\{?0\}?$/i, name: 'Loss-Conditioned Function', type: 'quantity_concept' },
  { pattern: /^h_\{?1\}?$/i, name: 'Fixation-Conditioned Function', type: 'quantity_concept' },
  { pattern: /^H_\{?h\}?$/i, name: 'Sweep-Linked Heterozygosity', type: 'quantity_concept' },
  { pattern: /^H_\{?0\}?$/i, name: 'Baseline Heterozygosity', type: 'quantity_concept' },
  { pattern: /^\\pi_\{?t\}?$/i, name: 'Time-Dependent Distribution', type: 'quantity_concept' },
  { pattern: /^\\pi\^\{\*\}$/i, name: 'Stationary Distribution', type: 'quantity_concept' },
  { pattern: /^\\nu_\{?n\}?$/i, name: 'Posterior Degrees of Freedom', type: 'quantity_concept' },
  { pattern: /^C\^\{-1\}$/i, name: 'Inverse Normalizing Constant', type: 'quantity_concept' },
];

export const GREEK_NAMES = new Map([
  ['alpha', 'Alpha'],
  ['beta', 'Beta'],
  ['gamma', 'Gamma'],
  ['delta', 'Delta'],
  ['epsilon', 'Epsilon'],
  ['varepsilon', 'Epsilon'],
  ['theta', 'Theta'],
  ['lambda', 'Lambda'],
  ['mu', 'Mean'],
  ['sigma', 'Standard Deviation'],
  ['rho', 'Correlation'],
  ['phi', 'Phi'],
  ['omega', 'Omega'],
  ['Delta', 'Change'],
]);

export const OPERATOR_SYMBOLS = new Set([
  '\\sum',
  '\\prod',
  '\\int',
  '\\partial',
  '\\Delta',
  '\\ln',
  '\\log',
  '\\exp',
  'Cov',
  'Var',
  'E',
  'Pr',
  'P',
  'log',
  'ln',
  'exp',
  'o',
]);

export const IGNORED_SYMBOLS = new Set([
  '\\boldsymbol',
  '\\widehat{\\boldsymbol}',
  '\\mathbf',
  '\\mathrm',
  'frac',
  'left',
  'right',
  'mathrm',
  'mathbf',
  'boldsymbol',
  'where',
]);

export const LATEX_COMMAND_SYMBOLS = new Set([
  'begin',
  'boldsymbol',
  'cdot',
  'cos',
  'end',
  'exp',
  'frac',
  'int',
  'left',
  'ln',
  'log',
  'mathrm',
  'mathbf',
  'over',
  'partial',
  'prod',
  'right',
  'sin',
  'sqrt',
  'sum',
  'tan',
  'text',
  'where',
]);

export const STRUCTURED_BLOCK_PRIORITY = new Map([
  ['definition', 6],
  ['derivation', 5],
  ['proposition', 4],
  ['discussion', 3],
]);

export const BAD_CONCEPT_PHRASE = /\b(first term|second term|third term|large parentheses|where|which|given that|note that|following set|standard approach|value for and|if gaussian|for gaussian|letting|assuming|subtracting|yielding|generated|is given|computed|calculated)\b/i;
export const BAD_CONCEPT_NAME = /^(first|second|third|last|following|if|for|when|while|satisfies|most robust approach|additional technical restriction|within-generation change is not influenced)\b/i;
export const SENTENCE_START_REPAIRS = [
  [/^qual to\b/i, 'The probability of moving from i to j'],
  [/^he parental\b/i, 'The parental'],
  [/^ose that\b/i, 'Suppose that'],
  [/^rait value\b/i, 'Trait value'],
  [/^nt applies\b/i, 'The argument applies'],
  [/^der neutrality\b/i, 'Under neutrality'],
];

export const CONCEPT_DEFINITIONS = new Map([
  ['wright-fisher transition probability', 'Probability that a Wright-Fisher population moves from allele count i to allele count j in one generation.'],
  ['transition probability', 'Probability of moving from one state to another in a stochastic model.'],
  ['probability', 'A quantity measuring how likely an event or state transition is.'],
  ['population size', 'The number of individuals or gene copies represented by the population model.'],
  ['count', 'A discrete number of items, individuals, or events.'],
  ['variable', 'A placeholder quantity whose value can change within the equation.'],
  ['time', 'A quantity indexing the stage, generation, or interval of the process.'],
  ['mean', 'The average value of a quantity in the relevant distribution or population.'],
  ['delta', 'A local change or increment in the modeled quantity.'],
  ['change', 'A difference or increment showing how the modeled quantity shifts between states, generations, or parameter values.'],
  ['index', 'A position marker used to identify a class, state, or summation term.'],
  ['frequency', 'The relative share of a class or type in the population.'],
  ['class frequency', 'The frequency assigned to one class or type in a population sum.'],
  ['trait value', 'The numerical value of the phenotype or quantitative trait being modeled.'],
  ['mean trait value', 'The population average of the trait value across all classes or individuals.'],
  ['class trait value', 'The trait value associated with one class or type.'],
  ['fitness', 'A measure of reproductive success or contribution to the next generation.'],
  ['absolute fitness', 'Fitness measured on an absolute scale before normalization.'],
  ['mean fitness', 'The population average of fitness values.'],
  ['fitness width', 'A scale parameter controlling how quickly fitness declines away from the optimum.'],
  ['optimal trait value', 'The trait value at which the fitness function reaches its optimum.'],
  ['strength of stabilizing selection', 'A parameter describing how strongly selection pulls trait values toward an optimum.'],
  ['selection differential', 'The change in mean trait value caused by selection before transmission.'],
  ['response', 'The change in mean trait value observed after inheritance or transmission.'],
  ['benefit', 'A positive effect or payoff contributed by a trait, behavior, allele, or interaction in the local model.'],
  ['cost', 'A negative effect or tradeoff subtracted from a payoff, fitness, or response term in the local model.'],
  ['response variable', 'The modeled output or observed quantity whose value is being predicted, transformed, or explained.'],
  ['cumulative response', 'The accumulated response measured across time or generations.'],
  ['cumulative selection differential', 'The accumulated selection differential across time or generations.'],
  ['selected population', 'The population or line subjected to selection.'],
  ['control population', 'The control population or line used as the comparison baseline.'],
  ['selected population mean trait value', 'The observed mean trait value for the selected population at the indexed time.'],
  ['control population mean trait value', 'The observed mean trait value for the control population at the indexed time.'],
  ['variance', 'A measure of spread around the mean.'],
  ['additive genetic variance', 'The portion of trait variance attributable to additive genetic effects, often denoted sigma_A^2.'],
  ['change in additive genetic variance', 'The change in additive genetic variance between the compared generations, states, or parameter settings.'],
  ['direct additive genetic variance', 'The additive genetic variance attributable to direct genetic effects on an individual trait or phenotype.'],
  ['associative additive genetic variance', 'The additive genetic variance attributable to associative genetic effects expressed through social or group interactions.'],
  ['total breeding value variance', 'The variance of total breeding values, combining direct and associative additive genetic effects.'],
  ['trait variance', 'The total variance of the trait value in the population or sample, often denoted sigma_z^2.'],
  ['environmental variance', 'The portion of phenotypic variance attributable to environmental or residual effects.'],
  ['covariance', 'A measure of how two quantities vary together.'],
  ['correlation', 'A standardized measure of the strength and direction of association between two quantities.'],
  ['expectation', 'The average value predicted by a probability distribution.'],
  ['likelihood', 'A function of model parameters proportional to the probability or density assigned to the observed data.'],
  ['likelihood function', 'A function of model parameters proportional to the probability or density assigned to the observed data.'],
  ['estimated expectation', 'An estimated expected value obtained by plugging parameter estimates into the expectation formula.'],
  ['estimated expected segregating sites', 'The estimated expected number of segregating sites for a locus or site class under the fitted model.'],
  ['estimated expected divergence', 'The estimated expected divergence for a locus or site class under the fitted model.'],
  ['expected quantity', 'The expected value of the quantity inside the expectation operator.'],
  ['expected order statistic', 'The expected value of a ranked sample observation, such as the smallest or kth ordered value.'],
  ['expected segregating sites', 'The expected number of segregating sites under the model.'],
  ['expected divergence', 'The expected divergence under the model.'],
  ['expected polymorphism', 'The expected polymorphism under the model.'],
  ['expected silent-site divergence', 'The expected amount of divergence at silent sites under the model.'],
  ['expected replacement-site divergence', 'The expected amount of divergence at replacement sites under the model.'],
  ['expected silent-site polymorphism', 'The expected amount of polymorphism at silent sites under the model.'],
  ['expected replacement-site polymorphism', 'The expected amount of polymorphism at replacement sites under the model.'],
  ['coefficient', 'A scalar multiplier that controls the size of a term in the formula.'],
  ['alpha', 'A model parameter or distribution-shape parameter named alpha in the local context.'],
  ['beta', 'A model parameter, regression coefficient, or distribution-shape parameter named beta in the local context.'],
  ['standard deviation', 'A square-root scale measure of spread around the mean.'],
  ['eigenvalue', 'A scalar value associated with a matrix transformation or correlation structure.'],
  ['identity matrix', 'A matrix with ones on the diagonal and zeros elsewhere.'],
  ['parameter vector', 'A collection of model parameters treated as one vector.'],
  ['vector or matrix quantity', 'A structured mathematical quantity represented as a vector or matrix.'],
  ['additive matrix exponentiation', 'A matrix exponentiation operation applied to the additive relationship or transition matrix.'],
  ['order term', 'A remainder term describing the asymptotic size of an expression.'],
  ['distance', 'A measure of separation between states, values, or functions.'],
  ['function', 'A rule that maps inputs to outputs in the model.'],
  ['rate', 'A parameter describing how quickly a process occurs.'],
  ['selection coefficient', 'A parameter measuring the strength of selection.'],
  ['mutation rate', 'A parameter measuring the probability of mutation per generation.'],
  ['recombination rate', 'The rate at which recombination separates linked loci.'],
  ['baseline recombination rate', 'The reference recombination rate used to scale linked-site effects.'],
  ['initial allele frequency', 'The allele frequency at the starting point of the process.'],
  ['variance function', 'A function describing local variance in a diffusion or stochastic process.'],
  ['information', 'A quantity measuring how much data or a likelihood constrains a parameter.'],
  ['bayes factor', 'A ratio comparing how strongly data support one hypothesis over another.'],
  ['fixation integral', 'An integral used to compute fixation-related quantities.'],
  ['probability density', 'A function whose integral gives probability over a continuous range.'],
  ['pi constant', 'The mathematical constant pi used in analytic expressions.'],
  ['stationary distribution', 'A distribution that remains unchanged under the transition dynamics.'],
  ['replacement-site divergence', 'The amount of divergence at replacement, amino-acid-changing sites between species.'],
  ['silent-site divergence', 'The amount of divergence at silent sites, used as a neutral reference in MK-style tests.'],
  ['replacement-site polymorphism', 'The amount of within-species polymorphism at replacement, amino-acid-changing sites.'],
  ['silent-site polymorphism', 'The amount of within-species polymorphism at silent sites, used as the neutral polymorphism reference.'],
  ['replacement-site divergence per gene', 'The replacement-site divergence measured for the indexed gene in a multi-gene MK-style estimator.'],
  ['silent-site divergence per gene', 'The silent-site divergence measured for the indexed gene and used as the neutral divergence reference.'],
  ['replacement-site polymorphism per gene', 'The replacement-site polymorphism measured for the indexed gene in a multi-gene MK-style estimator.'],
  ['silent-site polymorphism per gene', 'The silent-site polymorphism measured for the indexed gene and used as the neutral polymorphism reference.'],
  ['replacement-site segregating sites', 'The count of segregating replacement sites in the sample.'],
  ['silent-site segregating sites', 'The count of segregating silent sites in the sample.'],
  ['replacement-site mutation rate', 'The mutation rate assigned to replacement, amino-acid-changing sites.'],
  ['silent-site mutation rate', 'The mutation rate assigned to silent sites.'],
  ['replacement-site theta', 'The neutral diversity parameter for replacement sites.'],
  ['silent-site theta', 'The neutral diversity parameter for silent sites.'],
  ['replacement-site count', 'The number of replacement, amino-acid-changing sites.'],
  ['silent-site count', 'The number of silent sites.'],
  ['neutral replacement substitutions', 'The expected number of replacement substitutions under the neutral baseline.'],
  ['adaptive replacement substitutions', 'The number of replacement substitutions attributed to adaptive evolution.'],
  ['estimated adaptive replacement substitutions', 'An estimator for the number of adaptive replacement substitutions.'],
  ['estimated fraction of adaptive replacement substitutions', 'An estimator for the fraction of replacement substitutions that are adaptive.'],
  ['neutrality index', 'The MK-test odds ratio comparing replacement and silent polymorphism-divergence ratios.'],
  ['tarone-greenland neutrality index', 'A weighted neutrality index combining per-gene MK odds ratios across multiple genes.'],
  ['direction of selection statistic', 'A statistic comparing the fraction of replacement divergence with the fraction of replacement polymorphism.'],
  ['estimated fraction of adaptive substitutions', 'An estimator for the fraction of substitutions attributed to adaptive evolution.'],
  ['gamma function', 'A continuous extension of the factorial function.'],
  ['degrees of freedom', 'A parameter controlling the shape of a t or chi-square related distribution.'],
  ['posterior degrees of freedom', 'The degrees-of-freedom parameter after conditioning on observed data.'],
  ['parameter', 'An unknown or fixed quantity that controls a model.'],
  ['parameter vector', 'A collection of model parameters treated as one vector.'],
  ['estimator', 'A statistic used to estimate an unknown parameter.'],
  ['estimator vector', 'A vector-valued statistic used to estimate several parameters.'],
  ['data vector', 'The observed data represented as a vector.'],
  ['covariance matrix', 'A matrix describing variances and covariances among variables.'],
  ['wishart matrix', 'A random positive-definite matrix used in Wishart or inverse-Wishart models.'],
  ['acceptance rate', 'The probability or frequency of accepting a proposed move in a sampling algorithm.'],
  ['monte carlo estimate', 'An estimate computed from random samples.'],
  ['estimated function', 'A function estimated from data or simulation output.'],
  ['loss-conditioned function', 'A function conditioned on paths leading to loss.'],
  ['fixation-conditioned function', 'A function conditioned on paths leading to fixation.'],
  ['natural logarithm', 'The logarithm with base e, used to turn multiplicative changes into additive scale.'],
  ['exponential function', 'The inverse of the natural logarithm, often used to express multiplicative decay or growth.'],
  ['heterozygosity', 'The probability that two randomly sampled alleles at a locus are different.'],
  ['inbreeding coefficient', 'The probability that two alleles at a locus are identical by descent.'],
  ['sweep-linked heterozygosity', 'Heterozygosity at a neutral locus linked to a selected site after a selective sweep.'],
  ['baseline heterozygosity', 'The reference heterozygosity level used before or without the sweep effect.'],
  ['expected heterozygosity', 'The expected level of genetic diversity, often measured by nucleotide diversity.'],
  ['decline in heterozygosity', 'The proportional reduction in genetic diversity relative to a reference level.'],
  ['recessive sweep recombination scale', 'A dimensionless parameter combining recombination, effective population size, and selection strength for a fully recessive sweep.'],
  ['characteristic dispersal length', 'The spatial length scale controlling how far the signal of a geographically structured sweep extends.'],
  ['extended selection gradient vector', 'Morrissey’s path-analysis selection gradient vector that incorporates indirect paths through the total-effect matrix.'],
  ['time-dependent distribution', 'A probability distribution indexed by time.'],
  ['inverse normalizing constant', 'The reciprocal of a constant that makes a probability distribution integrate to one.'],
  ['additive genetic value', 'The additive genetic contribution to an individual or trait value.'],
  ['total additive genetic value', 'The additive genetic value aggregated over a group or total phenotype.'],
  ['inclusive-fitness breeding value', 'A breeding value measured through inclusive-fitness effects.'],
  ['fitness breeding value', 'The additive genetic component associated with fitness.'],
  ['trait breeding value', 'The additive genetic component associated with the trait.'],
  ['mean trait breeding value', 'The population mean of the trait breeding value.'],
  ['estimated relationship matrix', 'An estimated matrix of genetic relationships between individuals.'],
  ['additive genetic component', 'A component representing additive genetic contribution in the model.'],
  ['power of additive matrix', 'A matrix exponentiation operation applied to the additive relationship or transition matrix.'],
  ['among-block variance', 'The variance among environmental or experimental blocks in stratified selection.'],
  ['genetic variance', 'The genetic component of phenotypic variance in the local quantitative-genetic model.'],
  ['within-block environmental variance', 'The residual environmental variance within blocks after stratification.'],
  ['class selection coefficient', 'A selection coefficient assigned to one class or genotype.'],
  ['class fitness', 'The fitness assigned to one class, genotype, or category in a population sum.'],
  ['state probability', 'The probability assigned to one state or category in a stochastic model.'],
  ['theta', 'A model parameter conventionally denoted theta in the local context.'],
  ['omega', 'A model parameter conventionally denoted omega in the local context; its biological role is determined by the surrounding equation.'],
  ['gamma', 'A model parameter or special-function quantity conventionally denoted gamma in the local context.'],
  ['lambda', 'A model parameter, multiplier, rate, or eigenvalue conventionally denoted lambda in the local context.'],
  ['kappa', 'A model parameter conventionally denoted kappa in the local context.'],
  ['tau', 'A time-scale or model parameter conventionally denoted tau in the local context.'],
]);

export const CONCEPT_DEFINITIONS_ZH = new Map([
  ['wright-fisher transition probability', 'Wright-Fisher 模型中，群体从一个等位基因计数状态转移到另一个状态的概率。'],
  ['transition probability', '随机过程从一个状态进入另一个状态的概率。'],
  ['probability', '衡量某个事件或状态转移发生可能性的数量。'],
  ['population size', '模型中表示的个体数或基因拷贝数。'],
  ['count', '对个体、事件或类别数量的离散计数。'],
  ['variable', '公式中取值可以变化的占位量。'],
  ['time', '表示过程所处阶段、世代或时间间隔的量。'],
  ['mean', '相关分布或群体中某个量的平均值。'],
  ['delta', '模型中某个量的局部变化或增量。'],
  ['index', '用于标记类别、状态或求和项位置的下标。'],
  ['frequency', '某个类别或类型在群体中的相对占比。'],
  ['class frequency', '群体求和中某一类别或类型对应的频率。'],
  ['trait value', '表型或数量性状在模型中的数值。'],
  ['mean trait value', '群体中性状值的平均水平。'],
  ['class trait value', '某一类别或类型对应的性状值。'],
  ['fitness', '衡量个体繁殖成功或对下一代贡献的量。'],
  ['absolute fitness', '归一化之前、按绝对尺度衡量的适合度。'],
  ['mean fitness', '群体中适合度值的平均水平。'],
  ['fitness width', '控制性状偏离最优值时适合度下降速度的尺度参数。'],
  ['optimal trait value', '使适合度函数达到最大值的性状取值。'],
  ['strength of stabilizing selection', '描述稳定化选择把性状拉向最优值强度的参数。'],
  ['selection differential', '选择作用在遗传传递之前造成的平均性状值变化。'],
  ['response', '遗传或传递之后观察到的平均性状值变化。'],
  ['response variable', '模型中被预测、变换或解释的输出量或观测量。'],
  ['cumulative response', '随时间或世代累积得到的选择响应。'],
  ['cumulative selection differential', '随时间或世代累积得到的选择差。'],
  ['selected population', '受到选择处理的群体或品系。'],
  ['control population', '作为比较基线的对照组群体或对照品系。'],
  ['selected population mean trait value', '指定时间点中，选择组群体的观测平均性状值。'],
  ['control population mean trait value', '指定时间点中，对照组群体的观测平均性状值。'],
  ['variance', '衡量一个量围绕平均值分散程度的指标。'],
  ['additive genetic variance', '性状方差中由加性遗传效应解释的部分，常记为 sigma_A^2。'],
  ['direct additive genetic variance', '由直接遗传效应解释的加性遗传方差，通常对应个体自身性状或表型的遗传贡献。'],
  ['associative additive genetic variance', '由社群或群体互动中表现出来的关联遗传效应解释的加性遗传方差。'],
  ['total breeding value variance', '总育种值的方差，综合直接和关联加性遗传效应。'],
  ['trait variance', '群体或样本内性状值的总方差，常记为 sigma_z^2。'],
  ['environmental variance', '由环境或残差效应解释的表型方差部分。'],
  ['covariance', '衡量两个量共同变化方向和强度的指标。'],
  ['correlation', '标准化地衡量两个量之间关联强度和方向的指标。'],
  ['expectation', '由概率分布预测出的平均值。'],
  ['likelihood', '作为模型参数函数的似然，和观测数据在该模型下的概率或密度成比例。'],
  ['likelihood function', '作为模型参数函数的似然，和观测数据在该模型下的概率或密度成比例。'],
  ['estimated expectation', '把参数估计值代入期望公式后得到的估计期望值。'],
  ['estimated expected segregating sites', '在拟合模型下，对某个位点或位点类别的分离位点数期望所作的估计。'],
  ['estimated expected divergence', '在拟合模型下，对某个位点或位点类别的分化量期望所作的估计。'],
  ['expected quantity', '期望算子内部数量在模型下的期望值。'],
  ['expected segregating sites', '模型下分离位点数的期望值。'],
  ['expected divergence', '模型下分化量的期望值。'],
  ['expected polymorphism', '模型下多态性数量的期望值。'],
  ['expected silent-site divergence', '模型下沉默位点分化量的期望值。'],
  ['expected replacement-site divergence', '模型下替换位点分化量的期望值。'],
  ['expected silent-site polymorphism', '模型下沉默位点多态性数量的期望值。'],
  ['expected replacement-site polymorphism', '模型下替换位点多态性数量的期望值。'],
  ['coefficient', '控制公式中某一项大小的乘数。'],
  ['alpha', '局部模型中记为 alpha 的参数或分布形状参数。'],
  ['beta', '局部模型中记为 beta 的参数、回归系数或分布形状参数。'],
  ['standard deviation', '方差的平方根，用来表示分散程度的尺度。'],
  ['eigenvalue', '矩阵变换或相关结构中的特征值。'],
  ['identity matrix', '对角线为 1、其他位置为 0 的矩阵。'],
  ['parameter', '控制模型行为的未知量或固定量。'],
  ['parameter vector', '把多个模型参数作为一个向量整体表示。'],
  ['estimator', '用于估计未知参数的统计量。'],
  ['estimator vector', '用于同时估计多个参数的向量统计量。'],
  ['data vector', '以向量形式表示的观测数据。'],
  ['vector or matrix quantity', '以向量或矩阵形式表示的结构化数学量。'],
  ['covariance matrix', '描述多个变量方差和协方差的矩阵。'],
  ['wishart matrix', 'Wishart 或逆 Wishart 模型中使用的正定随机矩阵。'],
  ['order term', '描述表达式渐近规模的余项。'],
  ['distance', '衡量状态、数值或函数之间分离程度的量。'],
  ['function', '把输入映射为输出的规则。'],
  ['rate', '描述某个过程发生快慢的参数。'],
  ['selection coefficient', '衡量选择强度的参数。'],
  ['mutation rate', '衡量每一代发生突变概率的参数。'],
  ['recombination rate', '重组率表示连锁位点被重组分开的速率，决定中性位点逃离选择扫荡影响的机会。'],
  ['baseline recombination rate', '基准重组率用于给连锁位点效应定尺度，常作为比较遗传多样性下降幅度的参照。'],
  ['initial allele frequency', '初始等位基因频率表示过程开始时某个等位基因在群体中的相对占比。'],
  ['variance function', '描述扩散或随机过程中局部方差的函数。'],
  ['information', '衡量数据或似然函数对参数约束程度的量。'],
  ['bayes factor', '比较数据支持两个假设强弱的比值。'],
  ['fixation integral', '用于计算固定相关数量的积分。'],
  ['probability density', '连续变量中积分后得到概率的函数。'],
  ['pi constant', '圆周率 π，是解析表达式中使用的数学常数。'],
  ['stationary distribution', '在转移动力学下保持不变的概率分布。'],
  ['replacement-site divergence', '替换位点（会改变氨基酸的位点）在物种之间积累的分化量。'],
  ['silent-site divergence', '沉默位点在物种之间积累的分化量，常作为 MK 检验中的中性参照。'],
  ['replacement-site polymorphism', '物种内替换位点（会改变氨基酸的位点）的多态性数量。'],
  ['silent-site polymorphism', '物种内沉默位点的多态性数量，常作为中性多态性参照。'],
  ['replacement-site divergence per gene', '多基因 MK 类估计中，第 i 个基因的替换位点分化量。'],
  ['silent-site divergence per gene', '多基因 MK 类估计中，第 i 个基因的沉默位点分化量，作为中性分化参照。'],
  ['replacement-site polymorphism per gene', '多基因 MK 类估计中，第 i 个基因的替换位点多态性。'],
  ['silent-site polymorphism per gene', '多基因 MK 类估计中，第 i 个基因的沉默位点多态性，作为中性多态性参照。'],
  ['replacement-site segregating sites', '样本中替换位点的分离位点数量。'],
  ['silent-site segregating sites', '样本中沉默位点的分离位点数量。'],
  ['replacement-site mutation rate', '替换位点对应的突变率。'],
  ['silent-site mutation rate', '沉默位点对应的突变率。'],
  ['replacement-site theta', '替换位点对应的中性多样性参数 θ。'],
  ['silent-site theta', '沉默位点对应的中性多样性参数 θ。'],
  ['replacement-site count', '替换位点（会改变氨基酸的位点）的数量。'],
  ['silent-site count', '沉默位点的数量。'],
  ['neutral replacement substitutions', '中性基线下预期出现的替换位点替换数。'],
  ['adaptive replacement substitutions', '归因于适应性演化的替换位点替换数。'],
  ['estimated adaptive replacement substitutions', '对适应性替换位点替换数量的估计。'],
  ['estimated fraction of adaptive replacement substitutions', '对替换位点替换中适应性部分比例的估计。'],
  ['neutrality index', 'MK 检验中的赔率比，用来比较替换位点和沉默位点的多态性/分化比例。'],
  ['tarone-greenland neutrality index', 'Tarone-Greenland 加权中性指数，用来把多个基因的 MK 赔率比合并起来。'],
  ['direction of selection statistic', '方向选择统计量，用替换位点分化比例减去替换位点多态性比例来判断选择方向。'],
  ['estimated fraction of adaptive substitutions', '对替换中由适应性演化造成的比例进行估计的统计量。'],
  ['gamma function', '阶乘函数在连续情形下的推广。'],
  ['degrees of freedom', '控制 t 分布或卡方相关分布形状的参数。'],
  ['posterior degrees of freedom', '在观测数据条件化之后得到的自由度参数。'],
  ['acceptance rate', '采样算法中接受候选移动的概率或频率。'],
  ['monte carlo estimate', '由随机样本计算得到的估计值。'],
  ['estimated function', '由数据或模拟结果估计出的函数。'],
  ['loss-conditioned function', '在路径最终丢失这一条件下定义的函数。'],
  ['fixation-conditioned function', '在路径最终固定这一条件下定义的函数。'],
  ['natural logarithm', '以 e 为底的对数，用来把乘法关系转到可加尺度上。'],
  ['exponential function', '自然对数的反函数，常用来表示按比例衰减或增长。'],
  ['heterozygosity', '杂合度表示随机抽取两个等位基因时二者不同的概率，是衡量遗传多样性的核心量。'],
  ['inbreeding coefficient', '近交系数表示一个位点上的两个等位基因同源同祖的概率。'],
  ['sweep-linked heterozygosity', '选择扫荡后，与受选择位点连锁的中性位点仍保留下来的杂合度。'],
  ['baseline heterozygosity', '作为参照的杂合度水平，通常表示没有扫荡影响或扫荡前的遗传多样性。'],
  ['expected heterozygosity', '期望杂合度表示模型预期的遗传多样性水平，在这里用核苷酸多样性来衡量。'],
  ['decline in heterozygosity', '杂合度下降表示遗传多样性相对基准水平的减少比例。'],
  ['recessive sweep recombination scale', '完全隐性选择扫荡中的重组尺度参数，η = c√(4Ne/s)，用来衡量中性位点通过重组逃离扫荡影响的机会。'],
  ['characteristic dispersal length', '地理结构软扫荡模型中的特征扩散长度，用来刻画有利突变扩散时影响范围的空间尺度。'],
  ['extended selection gradient vector', 'Morrissey 路径分析中的扩展选择梯度向量，把直接路径系数通过总效应矩阵转换为包含间接路径的选择梯度。'],
  ['time-dependent distribution', '随时间变化的概率分布。'],
  ['inverse normalizing constant', '使概率分布积分为 1 的归一化常数的倒数。'],
  ['additive genetic value', '个体或性状值中的加性遗传贡献。'],
  ['total additive genetic value', '在群体或总表型中汇总的加性遗传值。'],
  ['inclusive-fitness breeding value', '通过包容适合度效应衡量的育种值。'],
  ['fitness breeding value', '与适合度相关的加性遗传组成部分。'],
  ['trait breeding value', '与性状相关的加性遗传组成部分。'],
  ['mean trait breeding value', '群体中性状育种值的平均水平。'],
  ['estimated relationship matrix', '估计得到的个体遗传关系矩阵。'],
  ['additive genetic component', '表示加性遗传贡献的模型组成部分。'],
  ['power of additive matrix', '对加性关系矩阵或转移矩阵进行的矩阵幂运算。'],
  ['among-block variance', '分层选择中不同区组之间的环境或处理差异方差。'],
  ['genetic variance', '当前数量遗传模型中的遗传方差组成部分。'],
  ['within-block environmental variance', '分层后区组内部剩余的环境方差。'],
  ['class selection coefficient', '分配给某一类别或基因型的选择系数。'],
]);
