export const REVIEW_PRESERVED_FIELDS = [
  'concept_id',
  'concept_name',
  'concept_type',
  'definition',
  'definition_zh',
  'aliases',
  'evidence',
  'confidence',
  'review_status',
  'review_flags',
  'reviewed_by',
  'reviewed_at',
  'review_notes',
  'canonical_concept_id',
  'canonical_concept_name',
];

export const REVIEW_STATUSES = ['unreviewed', 'approved', 'rejected', 'edited', 'ambiguous', 'needs_revision', 'reviewed'];
export const CONCEPT_CALIBRATIONS = new Map([
  ['chapter8::formula_8.8b::defined::\\frac{H_{h}}{H_{0}}', {
    concept_name: 'Relative Sweep-Linked Heterozygosity',
    concept_type: 'quantity_concept',
    definition: 'The heterozygosity remaining after a sweep, expressed relative to the baseline heterozygosity H0.',
    definition_zh: '选择扫荡后保留下来的杂合度相对基准杂合度的比例，用来直接读出遗传多样性还剩多少。',
    aliases: ['\\frac{H_{h}}{H_{0}}', 'H_h/H_0', 'Relative Sweep-Linked Heterozygosity'],
    review_notes: 'Curated from Formula 8.8b: H_h/H_0 is approximated as 1 - p(0)^(2c/s).',
  }],
  ['chapter8::formula_8.8e::defined::\\eta', {
    concept_name: 'Recessive Sweep Recombination Scale',
    concept_type: 'quantity_concept',
    definition: 'A dimensionless recombination scale for a fully recessive sweep, eta = c sqrt(4Ne/s).',
    definition_zh: '完全隐性选择扫荡中的重组尺度参数，η = c√(4Ne/s)，用来衡量中性位点通过重组逃离扫荡影响的机会。',
    aliases: ['\\eta', 'eta', 'Recessive Sweep Recombination Scale'],
    review_notes: 'Curated from Formula 8.8e context: Ewing et al. show H_h/H_0 ≃ eta/(1+eta) where eta=c sqrt(4Ne/s).',
  }],
  ['chapter8::formula_8.23::defined::\\chi', {
    concept_name: 'Characteristic Dispersal Length',
    concept_type: 'quantity_concept',
    definition: 'The characteristic dispersal length in a geographically structured sweep model.',
    definition_zh: '地理结构软扫荡模型中的特征扩散长度，用来刻画有利突变扩散时影响范围的空间尺度。',
    aliases: ['\\chi', 'chi', 'Characteristic Dispersal Length'],
    review_notes: 'Curated from Formula 8.23 context: Ralph and Coop identify chi as the key characteristic dispersal length.',
  }],
  ['chapter30::formula_30.33c::defined::\\eta', {
    concept_name: 'Extended Selection Gradient Vector',
    concept_type: 'quantity_concept',
    definition: "Morrissey's extended selection gradient vector, computed from the total-effect matrix and path-analysis selection gradients.",
    definition_zh: 'Morrissey 路径分析中的扩展选择梯度向量，把直接路径系数通过总效应矩阵转换为包含间接路径的选择梯度。',
    aliases: ['\\boldsymbol{\\eta}', '\\eta', 'eta', 'Extended Selection Gradient Vector'],
    review_notes: 'Curated from Formula 30.33c subsection title and equation eta = Phi beta_pa.',
  }],
  ['chapter30::formula_30.33c::used::\\Phi', {
    concept_name: 'Total-Effect Matrix',
    concept_type: 'math_concept',
    definition: 'A matrix that converts direct path-analysis coefficients into total effects, including indirect pathways.',
    definition_zh: '总效应矩阵，把直接路径系数转换成包含间接路径在内的总效应。',
    aliases: ['\\Phi', 'Phi', 'Total-Effect Matrix'],
    review_notes: 'Curated from Formula 30.33c: eta = Phi beta_pa.',
  }],
  ['chapter30::formula_30.33c::used::\\beta', {
    concept_name: 'Path-Analysis Selection Gradient Vector',
    concept_type: 'quantity_concept',
    definition: 'A vector of direct selection gradients estimated in the path-analysis model.',
    definition_zh: '路径分析模型中的直接选择梯度向量，表示各条直接路径上的选择效应。',
    aliases: ['\\beta_{pa}', '\\beta', 'Path-Analysis Selection Gradient Vector'],
    review_notes: 'Curated from Formula 30.33c: beta_pa is transformed by Phi.',
  }],
  ['chapter18::formula_18.23a::defined::\\overline{z}_{s,t}', {
    concept_name: 'Selected Population Mean Trait Value',
    concept_type: 'quantity_concept',
    definition: 'The observed mean trait value for the selected population at time t.',
    definition_zh: '第 t 个时间点中，选择组群体的观测平均性状值。',
    aliases: ['\\overline{z}_{s,t}', 'selected population mean', 'Selected Population Mean Trait Value'],
    review_notes: 'Curated from the local text: selected (s) and control (c) population means are decomposed in Equations 18.23a-b.',
  }],
  ['chapter18::formula_18.23a::used::s', {
    concept_name: 'Selected Population',
    concept_type: 'domain_concept',
    definition: 'The population or line subjected to selection.',
    definition_zh: '受到选择处理的群体或品系。',
    aliases: ['s', 'selected', 'Selected Population'],
    review_notes: 'Curated from the local text: selected (s) and control (c) population.',
  }],
  ['chapter18::formula_18.23a::used::t', {
    concept_name: 'Time',
    concept_type: 'quantity_concept',
    definition: 'A quantity indexing the stage, generation, or interval of the process.',
    definition_zh: '表示过程所处阶段、世代或时间间隔的量。',
    aliases: ['t', 'Time'],
    review_notes: 'Curated for the selected population mean at time t.',
  }],
  ['chapter18::formula_18.23b::defined::\\overline{z}_{c,t}', {
    concept_name: 'Control Population Mean Trait Value',
    concept_type: 'quantity_concept',
    definition: 'The observed mean trait value for the control population at time t.',
    definition_zh: '第 t 个时间点中，对照组群体的观测平均性状值。',
    aliases: ['\\overline{z}_{c,t}', 'control population mean', 'Control Population Mean Trait Value'],
    review_notes: 'Curated from the local text: selected (s) and control (c) population means are decomposed in Equations 18.23a-b.',
  }],
  ['chapter18::formula_18.23b::used::c', {
    concept_name: 'Control Population',
    concept_type: 'domain_concept',
    definition: 'The control population or line used as the comparison baseline.',
    definition_zh: '作为比较基线的对照组群体或对照品系。',
    aliases: ['c', 'control', 'Control Population'],
    review_notes: 'Curated from the local text: selected (s) and control (c) population.',
  }],
  ['chapter18::formula_18.23b::used::t', {
    concept_name: 'Time',
    concept_type: 'quantity_concept',
    definition: 'A quantity indexing the stage, generation, or interval of the process.',
    definition_zh: '表示过程所处阶段、世代或时间间隔的量。',
    aliases: ['t', 'Time'],
    review_notes: 'Curated for the control population mean at time t.',
  }],
  ['chapter18::formula_18.25b::defined::R_{C}', {
    concept_name: 'Cumulative Response',
    concept_type: 'quantity_concept',
    definition: 'The cumulative response, computed as the selected population mean minus the control population mean at time t.',
    definition_zh: '第 t 个时间点中，选择组平均性状值与对照组平均性状值之差表示的累积响应。',
    aliases: ['R_{C}', 'R_C', 'cumulative response', 'Cumulative Response'],
    review_notes: 'Curated from the local text: R_C(t) is introduced in the section describing cumulative responses and differentials.',
  }],
  ['chapter18::formula_18.25b::used::c', {
    concept_name: 'Control Population',
    concept_type: 'domain_concept',
    definition: 'The control population or line used as the comparison baseline.',
    definition_zh: '作为比较基线的对照组群体或对照品系。',
    aliases: ['c', 'control', 'Control Population'],
    review_notes: 'Curated from the local text: selected (s) and control (c) population.',
  }],
  ['chapter18::formula_18.25b::used::s', {
    concept_name: 'Selected Population',
    concept_type: 'domain_concept',
    definition: 'The population or line subjected to selection.',
    definition_zh: '受到选择处理的群体或品系。',
    aliases: ['s', 'selected', 'Selected Population'],
    review_notes: 'Curated from the local text: selected (s) and control (c) population.',
  }],
  ['chapter18::formula_18.25b::used::t', {
    concept_name: 'Time',
    concept_type: 'quantity_concept',
    definition: 'A quantity indexing the stage, generation, or interval of the process.',
    definition_zh: '表示过程所处阶段、世代或时间间隔的量。',
    aliases: ['t', 'Time'],
    review_notes: 'Curated for the cumulative response expression R_C(t).',
  }],
  ['chapter18::formula_18.25c::defined::S_{t}', {
    concept_name: 'Selection Differential',
    concept_type: 'quantity_concept',
    definition: 'The selection differential for time t.',
    definition_zh: '第 t 个时间点对应的选择差。',
    aliases: ['S_{t}', 'selection differential', 'Selection Differential'],
    review_notes: 'Curated from the local text: responses and differentials are estimated together in Equations 18.25b-d.',
  }],
  ['chapter18::formula_18.25d::defined::S_{C}', {
    concept_name: 'Cumulative Selection Differential',
    concept_type: 'quantity_concept',
    definition: 'The cumulative selection differential up to time t.',
    definition_zh: '截至第 t 个时间点累积得到的选择差。',
    aliases: ['S_{C}', 'S_C', 'cumulative selection differential', 'Cumulative Selection Differential'],
    review_notes: 'Curated from the local text: S_C(t) is the cumulative selection differential.',
  }],
  ['appendix5::formula_A5.4::defined::\\theta', {
    concept_name: 'Vector Angle',
    concept_type: 'math_concept',
    definition: 'The angle between two vectors, computed from their normalized dot product.',
    aliases: ['\\theta', 'theta', 'Vector Angle'],
    review_notes: 'Curated for public appendix coverage: the formula defines the angle between two vectors from their dot product.',
  }],
  ['appendix5::formula_A5.15::defined::\\mathbf{I}', {
    concept_name: 'Identity Matrix',
    concept_type: 'math_concept',
    definition: 'A matrix with ones on the diagonal and zeros elsewhere.',
    aliases: ['\\mathbf{I}', 'I', 'Identity Matrix'],
    review_notes: 'Curated for public appendix coverage: the identity matrix appears in the characteristic matrix expression.',
  }],
  ['appendix5::formula_A5.48::defined::\\phi', {
    concept_name: 'Multivariate Normal Density',
    concept_type: 'math_concept',
    definition: 'A probability density for a normally distributed vector, parameterized by a mean vector and covariance matrix.',
    aliases: ['\\phi', 'phi', 'Multivariate Normal Density', 'Probability Density'],
    review_notes: 'Curated for public appendix coverage: the formula gives the multivariate normal density.',
  }],
  ['appendix5::formula_A5.56::defined::\\lambda_{i}', {
    concept_name: 'Eigenvalue',
    concept_type: 'math_concept',
    definition: 'A scalar value associated with a matrix transformation or covariance structure.',
    aliases: ['\\lambda_{i}', 'lambda_i', 'Eigenvalue'],
    review_notes: 'Curated for public appendix coverage: the formula expresses variance share through covariance-matrix eigenvalues.',
  }],
  ['appendix6::formula_A6.2::defined::\\varphi', {
    concept_name: 'Multivariate Normal Density',
    concept_type: 'math_concept',
    definition: 'A probability density for a normally distributed vector, parameterized by a mean vector and covariance matrix.',
    aliases: ['\\varphi', 'varphi', 'Multivariate Normal Density', 'Probability Density'],
    review_notes: 'Curated for public appendix coverage: the formula differentiates the multivariate normal density.',
  }],
  ['appendix6::formula_A6.10::defined::\\widehat{\\boldsymbol{\\beta}}', {
    concept_name: 'Fixed-Effect Estimator Vector',
    concept_type: 'quantity_concept',
    definition: 'A vector of estimated fixed-effect coefficients used in mixed-model equations.',
    aliases: ['\\widehat{\\boldsymbol{\\beta}}', 'beta hat', 'Fixed-Effect Estimator Vector'],
    review_notes: 'Curated for public appendix coverage: the formula solves for the estimated fixed-effect coefficient vector.',
  }],
  ['appendix6::formula_A6.14::defined::g', {
    concept_name: 'Lagrangian Objective',
    concept_type: 'math_concept',
    definition: 'An augmented objective function used to optimize a function subject to a constraint.',
    aliases: ['g', 'Lagrangian Objective'],
    review_notes: 'Curated for public appendix coverage: the formula constructs the Lagrangian objective for constrained optimization.',
  }],
  ['appendix6::formula_A6.15::defined::\\lambda', {
    concept_name: 'Lagrange Multiplier',
    concept_type: 'math_concept',
    definition: 'A parameter introduced to optimize a function while enforcing a constraint.',
    aliases: ['\\lambda', 'lambda', 'Lagrange Multiplier'],
    review_notes: 'Curated for public appendix coverage: the formula uses lambda as the multiplier in the constrained-gradient condition.',
  }],
]);

export const PRODUCT_GENERIC_CONCEPT_NAMES = new Set([
  'chi',
  'coefficient',
  'count',
  'distance',
  'eta',
  'expression',
  'fact',
  'function',
  'index',
  'mean',
  'offspring',
  'rate',
  'ratio of',
  'same logic',
  'there',
  'time index',
  'value',
  'values',
  'variable',
]);

export const COMMON_SYMBOL_NAMES = new Map([
  ['N', 'Population Size'],
  ['n', 'Count'],
  ['i', 'Index'],
  ['j', 'Index'],
  ['k', 'Index'],
  ['t', 'Time'],
  ['p', 'Probability'],
  ['q', 'Frequency'],
  ['w', 'Fitness'],
  ['W', 'Absolute Fitness'],
  ['z', 'Trait Value'],
  ['x', 'Variable'],
  ['y', 'Response Variable'],
  ['S', 'Selection Differential'],
  ['R', 'Response'],
  ['V', 'Variance'],
  ['C', 'Cost'],
  ['B', 'Benefit'],
  ['E', 'Expectation'],
  ['Cov', 'Covariance'],
  ['Var', 'Variance'],
  ['Pr', 'Probability'],
  ['P', 'Probability'],
  ['L', 'Likelihood'],
  ['a', 'Coefficient'],
  ['b', 'Coefficient'],
  ['d', 'Distance'],
  ['f', 'Function'],
  ['h', 'Function'],
  ['m', 'Mean'],
  ['o', 'Order Term'],
  ['r', 'Rate'],
  ['s', 'Selection Coefficient'],
  ['u', 'Mutation Rate'],
  ['v', 'Variance Function'],
  ['T', 'Time'],
  ['I', 'Information'],
  ['ln', 'Natural Logarithm'],
  ['\\ln', 'Natural Logarithm'],
  ['exp', 'Exponential Function'],
  ['\\exp', 'Exponential Function'],
  ['B_{0}', 'Bayes Factor'],
  ['I_{f}', 'Fixation Integral'],
  ['\\varphi', 'Probability Density'],
  ['\\phi', 'Probability Density'],
  ['\\pi', 'Stationary Distribution'],
  ['\\Gamma', 'Gamma Function'],
  ['\\nu', 'Degrees of Freedom'],
  ['\\theta', 'Parameter'],
  ['\\widehat{\\theta}', 'Estimator'],
  ['\\Theta', 'Parameter Vector'],
  ['\\boldsymbol{\\theta}', 'Parameter Vector'],
  ['\\widehat{\\boldsymbol{\\theta}}', 'Estimator Vector'],
  ['\\boldsymbol{\\Theta}', 'Parameter Vector'],
  ['\\mathbf{x}', 'Data Vector'],
  ['\\mathbf{I}', 'Identity Matrix'],
  ['\\mathbf{V}', 'Covariance Matrix'],
  ['\\mathbf{W}', 'Wishart Matrix'],
  ['\\mathrm{P}', 'Probability'],
  ['\\mathrm{V}', 'Variance'],
  ['\\mathrm{r}', 'Rate'],
  ['\\mathrm{a}', 'Acceptance Rate'],
  ['NI', 'Neutrality Index'],
  ['NI_{TG}', 'Tarone-Greenland Neutrality Index'],
  ['DoS', 'Direction of Selection Statistic'],
]);

export const SUBSCRIPT_SYMBOL_NAMES = [
  { pattern: /^D_\{?ai\}?$/i, name: 'Replacement-Site Divergence per Gene', type: 'quantity_concept' },
  { pattern: /^D_\{?si\}?$/i, name: 'Silent-Site Divergence per Gene', type: 'quantity_concept' },
  { pattern: /^P_\{?ai\}?$/i, name: 'Replacement-Site Polymorphism per Gene', type: 'quantity_concept' },
  { pattern: /^P_\{?si\}?$/i, name: 'Silent-Site Polymorphism per Gene', type: 'quantity_concept' },
  { pattern: /^D_\{?a\}?$/i, name: 'Replacement-Site Divergence', type: 'quantity_concept' },
  { pattern: /^D_\{?s\}?$/i, name: 'Silent-Site Divergence', type: 'quantity_concept' },
  { pattern: /^P_\{?a\}?$/i, name: 'Replacement-Site Polymorphism', type: 'quantity_concept' },
  { pattern: /^P_\{?s\}?$/i, name: 'Silent-Site Polymorphism', type: 'quantity_concept' },
  { pattern: /^S_\{?a\}?$/i, name: 'Replacement-Site Segregating Sites', type: 'quantity_concept' },
  { pattern: /^S_\{?s\}?$/i, name: 'Silent-Site Segregating Sites', type: 'quantity_concept' },
  { pattern: /^\\mu_\{?a\}?$/i, name: 'Replacement-Site Mutation Rate', type: 'quantity_concept' },
  { pattern: /^\\mu_\{?s\}?$/i, name: 'Silent-Site Mutation Rate', type: 'quantity_concept' },
  { pattern: /^\\theta_\{?a\}?$/i, name: 'Replacement-Site Theta', type: 'quantity_concept' },
  { pattern: /^\\theta_\{?s\}?$/i, name: 'Silent-Site Theta', type: 'quantity_concept' },
  { pattern: /^n_\{?a\}?$/i, name: 'Replacement-Site Count', type: 'quantity_concept' },
  { pattern: /^n_\{?s\}?$/i, name: 'Silent-Site Count', type: 'quantity_concept' },
  { pattern: /^D_\{?a,n\}?$/i, name: 'Neutral Replacement Substitutions', type: 'quantity_concept' },
  { pattern: /^\\eta_\{?a\}?$/i, name: 'Adaptive Replacement Substitutions', type: 'quantity_concept' },
  { pattern: /^\\widehat\{\\eta\}_\{?a\}?$/i, name: 'Estimated Adaptive Replacement Substitutions', type: 'quantity_concept' },
  { pattern: /^\\(?:overline|bar)\{?z\}?$/i, name: 'Mean Trait Value', type: 'quantity_concept' },
  { pattern: /^\\(?:overline|bar)\{?[Ww]\}?$/i, name: 'Mean Fitness', type: 'quantity_concept' },
  { pattern: /^A$/i, name: 'Additive Genetic Value', type: 'quantity_concept' },
  { pattern: /^A_\{?T(?:,n)?\}?$/i, name: 'Total Additive Genetic Value', type: 'quantity_concept' },
  { pattern: /^A_\{?incf\}?$/i, name: 'Inclusive-Fitness Breeding Value', type: 'quantity_concept' },
  { pattern: /^A_\{?w\}?$/i, name: 'Fitness Breeding Value', type: 'quantity_concept' },
  { pattern: /^A_\{?z\}?$/i, name: 'Trait Breeding Value', type: 'quantity_concept' },
  { pattern: /^\\overline\{A\}_\{?z\}?$/i, name: 'Mean Trait Breeding Value', type: 'quantity_concept' },
  { pattern: /^\\widehat\{A\}_\{?.+\}?$/i, name: 'Estimated Relationship Matrix', type: 'quantity_concept' },
  { pattern: /^A_\{?.+\}?$/i, name: 'Additive Genetic Component', type: 'quantity_concept' },
  { pattern: /^A\^\{?.+\}?$/i, name: 'Power of Additive Matrix', type: 'math_concept' },
  { pattern: /^\\widehat\{?\\boldsymbol\{?.+\}?\}?$/i, name: 'Estimator Vector', type: 'quantity_concept' },
  { pattern: /^\\boldsymbol\{?.+\}?$/i, name: 'Parameter Vector', type: 'quantity_concept' },
  { pattern: /^\\mathbf\{?I\}?$/i, name: 'Identity Matrix', type: 'math_concept' },
  { pattern: /^\\mathbf\{?.+\}?$/i, name: 'Vector or Matrix Quantity', type: 'math_concept' },
  { pattern: /^P_\{?ij\}?$/i, name: 'Wright-Fisher Transition Probability', type: 'quantity_concept' },
  { pattern: /^P_\{?.+\}?$/i, name: 'Probability', type: 'quantity_concept' },
  { pattern: /^s_\{?.+\}?$/i, name: 'Class Selection Coefficient', type: 'quantity_concept' },
  { pattern: /^q_\{?i\}?$/i, name: 'Class Frequency', type: 'quantity_concept' },
  { pattern: /^z_\{?i\}?$/i, name: 'Class Trait Value', type: 'quantity_concept' },
  { pattern: /^w_\{?i\}?$/i, name: 'Class Fitness', type: 'quantity_concept' },
  { pattern: /^x_\{?i\}?$/i, name: 'State Probability', type: 'quantity_concept' },
  { pattern: /^f_\{?t\}?$/i, name: 'Inbreeding Coefficient', type: 'quantity_concept' },
  { pattern: /^H_\{?t\}?$/i, name: 'Heterozygosity', type: 'quantity_concept' },
  { pattern: /^\\lambda_\{?.+\}?$/i, name: 'Eigenvalue', type: 'math_concept' },
  { pattern: /^\\mu_\{?z\}?$/i, name: 'Mean Trait Value', type: 'quantity_concept' },
  { pattern: /^\\mu_\{?.+\}?$/i, name: 'Mean', type: 'quantity_concept' },
  { pattern: /^c_\{?0\}?$/i, name: 'Baseline Recombination Rate', type: 'quantity_concept' },
  { pattern: /^p\(0\)$/i, name: 'Initial Allele Frequency', type: 'quantity_concept' },
  { pattern: /^p_\{?.+\}?$/i, name: 'Probability', type: 'quantity_concept' },
  { pattern: /^\\sigma_\{?A\}?\^\{?2\}?$/i, name: 'Additive Genetic Variance', type: 'quantity_concept' },
  { pattern: /^\\sigma_\{?B\}?\^\{?2\}?$/i, name: 'Among-Block Variance', type: 'quantity_concept' },
  { pattern: /^\\sigma_\{?G\}?\^\{?2\}?$/i, name: 'Genetic Variance', type: 'quantity_concept' },
  { pattern: /^\\sigma_\{?e\}?\^\{?2\}?$/i, name: 'Within-Block Environmental Variance', type: 'quantity_concept' },
  { pattern: /^\\sigma_\{?z\}?\^\{?2\}?$/i, name: 'Trait Variance', type: 'quantity_concept' },
  { pattern: /^\\sigma(?:_\{?.+\}?)?\^\{?2\}?$/i, name: 'Variance', type: 'quantity_concept' },
  { pattern: /^\\omega(?:\^\{?2\}?)?$/i, name: 'Fitness Width', type: 'quantity_concept' },
  { pattern: /^\\Theta$/, name: 'Parameter Vector', type: 'quantity_concept' },
  { pattern: /^\\theta$/, name: 'Optimal Trait Value', type: 'quantity_concept' },
  { pattern: /^V_\{?s\}?$/i, name: 'Strength of Stabilizing Selection', type: 'quantity_concept' },
  { pattern: /^z\^\{\*\}$/i, name: 'Optimal Trait Value', type: 'quantity_concept' },
  { pattern: /^\\widehat\{?I\}?$/i, name: 'Monte Carlo Estimate', type: 'quantity_concept' },
  { pattern: /^\\widehat\{?h\}?$/i, name: 'Estimated Function', type: 'quantity_concept' },
  { pattern: /^h_\{?0\}?$/i, name: 'Loss-Conditioned Function', type: 'quantity_concept' },
  { pattern: /^h_\{?1\}?$/i, name: 'Fixation-Conditioned Function', type: 'quantity_concept' },
  { pattern: /^H_\{?h\}?$/i, name: 'Sweep-Linked Heterozygosity', type: 'quantity_concept' },
  { pattern: /^H_\{?0\}?$/i, name: 'Baseline Heterozygosity', type: 'quantity_concept' },
  { pattern: /^\\pi_\{?t\}?$/i, name: 'Time-Dependent Distribution', type: 'quantity_concept' },
  { pattern: /^\\pi\^\{\*\}$/i, name: 'Stationary Distribution', type: 'quantity_concept' },
  { pattern: /^\\nu_\{?n\}?$/i, name: 'Posterior Degrees of Freedom', type: 'quantity_concept' },
  { pattern: /^C\^\{-1\}$/i, name: 'Inverse Normalizing Constant', type: 'quantity_concept' },
];

export const GREEK_NAMES = new Map([
  ['alpha', 'Alpha'],
  ['beta', 'Beta'],
  ['gamma', 'Gamma'],
  ['delta', 'Delta'],
  ['epsilon', 'Epsilon'],
  ['varepsilon', 'Epsilon'],
  ['theta', 'Theta'],
  ['lambda', 'Lambda'],
  ['mu', 'Mean'],
  ['sigma', 'Standard Deviation'],
  ['rho', 'Correlation'],
  ['phi', 'Phi'],
  ['omega', 'Omega'],
  ['Delta', 'Change'],
]);

export const OPERATOR_SYMBOLS = new Set([
  '\\sum',
  '\\prod',
  '\\int',
  '\\partial',
  '\\Delta',
  '\\ln',
  '\\log',
  '\\exp',
  'Cov',
  'Var',
  'E',
  'Pr',
  'P',
  'log',
  'ln',
  'exp',
  'o',
]);

export const IGNORED_SYMBOLS = new Set([
  '\\boldsymbol',
  '\\widehat{\\boldsymbol}',
  '\\mathbf',
  '\\mathrm',
  'frac',
  'left',
  'right',
  'mathrm',
  'mathbf',
  'boldsymbol',
  'where',
]);

export const LATEX_COMMAND_SYMBOLS = new Set([
  'begin',
  'boldsymbol',
  'cdot',
  'cos',
  'end',
  'exp',
  'frac',
  'int',
  'left',
  'ln',
  'log',
  'mathrm',
  'mathbf',
  'over',
  'partial',
  'prod',
  'right',
  'sin',
  'sqrt',
  'sum',
  'tan',
  'text',
  'where',
]);

export const STRUCTURED_BLOCK_PRIORITY = new Map([
  ['definition', 6],
  ['derivation', 5],
  ['proposition', 4],
  ['discussion', 3],
]);

export const BAD_CONCEPT_PHRASE = /\b(first term|second term|third term|large parentheses|where|which|given that|note that|following set|standard approach|value for and|if gaussian|for gaussian|letting|assuming|subtracting|yielding|generated|is given|computed|calculated)\b/i;
export const BAD_CONCEPT_NAME = /^(first|second|third|last|following|if|for|when|while|satisfies|most robust approach|additional technical restriction|within-generation change is not influenced)\b/i;
export const SENTENCE_START_REPAIRS = [
  [/^qual to\b/i, 'The probability of moving from i to j'],
  [/^he parental\b/i, 'The parental'],
  [/^ose that\b/i, 'Suppose that'],
  [/^rait value\b/i, 'Trait value'],
  [/^nt applies\b/i, 'The argument applies'],
  [/^der neutrality\b/i, 'Under neutrality'],
];

export const CONCEPT_DEFINITIONS = new Map([
  ['wright-fisher transition probability', 'Probability that a Wright-Fisher population moves from allele count i to allele count j in one generation.'],
  ['transition probability', 'Probability of moving from one state to another in a stochastic model.'],
  ['probability', 'A quantity measuring how likely an event or state transition is.'],
  ['population size', 'The number of individuals or gene copies represented by the population model.'],
  ['count', 'A discrete number of items, individuals, or events.'],
  ['variable', 'A placeholder quantity whose value can change within the equation.'],
  ['time', 'A quantity indexing the stage, generation, or interval of the process.'],
  ['mean', 'The average value of a quantity in the relevant distribution or population.'],
  ['delta', 'A local change or increment in the modeled quantity.'],
  ['index', 'A position marker used to identify a class, state, or summation term.'],
  ['frequency', 'The relative share of a class or type in the population.'],
  ['class frequency', 'The frequency assigned to one class or type in a population sum.'],
  ['trait value', 'The numerical value of the phenotype or quantitative trait being modeled.'],
  ['mean trait value', 'The population average of the trait value across all classes or individuals.'],
  ['class trait value', 'The trait value associated with one class or type.'],
  ['fitness', 'A measure of reproductive success or contribution to the next generation.'],
  ['absolute fitness', 'Fitness measured on an absolute scale before normalization.'],
  ['mean fitness', 'The population average of fitness values.'],
  ['fitness width', 'A scale parameter controlling how quickly fitness declines away from the optimum.'],
  ['optimal trait value', 'The trait value at which the fitness function reaches its optimum.'],
  ['strength of stabilizing selection', 'A parameter describing how strongly selection pulls trait values toward an optimum.'],
  ['selection differential', 'The change in mean trait value caused by selection before transmission.'],
  ['response', 'The change in mean trait value observed after inheritance or transmission.'],
  ['cumulative response', 'The accumulated response measured across time or generations.'],
  ['cumulative selection differential', 'The accumulated selection differential across time or generations.'],
  ['selected population', 'The population or line subjected to selection.'],
  ['control population', 'The control population or line used as the comparison baseline.'],
  ['selected population mean trait value', 'The observed mean trait value for the selected population at the indexed time.'],
  ['control population mean trait value', 'The observed mean trait value for the control population at the indexed time.'],
  ['variance', 'A measure of spread around the mean.'],
  ['covariance', 'A measure of how two quantities vary together.'],
  ['expectation', 'The average value predicted by a probability distribution.'],
  ['likelihood', 'A measure of how well a model explains observed data.'],
  ['coefficient', 'A scalar multiplier that controls the size of a term in the formula.'],
  ['alpha', 'A model parameter or distribution-shape parameter named alpha in the local context.'],
  ['beta', 'A model parameter, regression coefficient, or distribution-shape parameter named beta in the local context.'],
  ['standard deviation', 'A square-root scale measure of spread around the mean.'],
  ['eigenvalue', 'A scalar value associated with a matrix transformation or correlation structure.'],
  ['identity matrix', 'A matrix with ones on the diagonal and zeros elsewhere.'],
  ['parameter vector', 'A collection of model parameters treated as one vector.'],
  ['vector or matrix quantity', 'A structured mathematical quantity represented as a vector or matrix.'],
  ['order term', 'A remainder term describing the asymptotic size of an expression.'],
  ['distance', 'A measure of separation between states, values, or functions.'],
  ['function', 'A rule that maps inputs to outputs in the model.'],
  ['rate', 'A parameter describing how quickly a process occurs.'],
  ['selection coefficient', 'A parameter measuring the strength of selection.'],
  ['mutation rate', 'A parameter measuring the probability of mutation per generation.'],
  ['recombination rate', 'The rate at which recombination separates linked loci.'],
  ['baseline recombination rate', 'The reference recombination rate used to scale linked-site effects.'],
  ['initial allele frequency', 'The allele frequency at the starting point of the process.'],
  ['variance function', 'A function describing local variance in a diffusion or stochastic process.'],
  ['information', 'A quantity measuring how much data or a likelihood constrains a parameter.'],
  ['bayes factor', 'A ratio comparing how strongly data support one hypothesis over another.'],
  ['fixation integral', 'An integral used to compute fixation-related quantities.'],
  ['probability density', 'A function whose integral gives probability over a continuous range.'],
  ['pi constant', 'The mathematical constant pi used in analytic expressions.'],
  ['stationary distribution', 'A distribution that remains unchanged under the transition dynamics.'],
  ['replacement-site divergence', 'The amount of divergence at replacement, amino-acid-changing sites between species.'],
  ['silent-site divergence', 'The amount of divergence at silent sites, used as a neutral reference in MK-style tests.'],
  ['replacement-site polymorphism', 'The amount of within-species polymorphism at replacement, amino-acid-changing sites.'],
  ['silent-site polymorphism', 'The amount of within-species polymorphism at silent sites, used as the neutral polymorphism reference.'],
  ['replacement-site divergence per gene', 'The replacement-site divergence measured for the indexed gene in a multi-gene MK-style estimator.'],
  ['silent-site divergence per gene', 'The silent-site divergence measured for the indexed gene and used as the neutral divergence reference.'],
  ['replacement-site polymorphism per gene', 'The replacement-site polymorphism measured for the indexed gene in a multi-gene MK-style estimator.'],
  ['silent-site polymorphism per gene', 'The silent-site polymorphism measured for the indexed gene and used as the neutral polymorphism reference.'],
  ['replacement-site segregating sites', 'The count of segregating replacement sites in the sample.'],
  ['silent-site segregating sites', 'The count of segregating silent sites in the sample.'],
  ['replacement-site mutation rate', 'The mutation rate assigned to replacement, amino-acid-changing sites.'],
  ['silent-site mutation rate', 'The mutation rate assigned to silent sites.'],
  ['replacement-site theta', 'The neutral diversity parameter for replacement sites.'],
  ['silent-site theta', 'The neutral diversity parameter for silent sites.'],
  ['replacement-site count', 'The number of replacement, amino-acid-changing sites.'],
  ['silent-site count', 'The number of silent sites.'],
  ['neutral replacement substitutions', 'The expected number of replacement substitutions under the neutral baseline.'],
  ['adaptive replacement substitutions', 'The number of replacement substitutions attributed to adaptive evolution.'],
  ['estimated adaptive replacement substitutions', 'An estimator for the number of adaptive replacement substitutions.'],
  ['estimated fraction of adaptive replacement substitutions', 'An estimator for the fraction of replacement substitutions that are adaptive.'],
  ['neutrality index', 'The MK-test odds ratio comparing replacement and silent polymorphism-divergence ratios.'],
  ['tarone-greenland neutrality index', 'A weighted neutrality index combining per-gene MK odds ratios across multiple genes.'],
  ['direction of selection statistic', 'A statistic comparing the fraction of replacement divergence with the fraction of replacement polymorphism.'],
  ['estimated fraction of adaptive substitutions', 'An estimator for the fraction of substitutions attributed to adaptive evolution.'],
  ['gamma function', 'A continuous extension of the factorial function.'],
  ['degrees of freedom', 'A parameter controlling the shape of a t or chi-square related distribution.'],
  ['posterior degrees of freedom', 'The degrees-of-freedom parameter after conditioning on observed data.'],
  ['parameter', 'An unknown or fixed quantity that controls a model.'],
  ['parameter vector', 'A collection of model parameters treated as one vector.'],
  ['estimator', 'A statistic used to estimate an unknown parameter.'],
  ['estimator vector', 'A vector-valued statistic used to estimate several parameters.'],
  ['data vector', 'The observed data represented as a vector.'],
  ['covariance matrix', 'A matrix describing variances and covariances among variables.'],
  ['wishart matrix', 'A random positive-definite matrix used in Wishart or inverse-Wishart models.'],
  ['acceptance rate', 'The probability or frequency of accepting a proposed move in a sampling algorithm.'],
  ['monte carlo estimate', 'An estimate computed from random samples.'],
  ['estimated function', 'A function estimated from data or simulation output.'],
  ['loss-conditioned function', 'A function conditioned on paths leading to loss.'],
  ['fixation-conditioned function', 'A function conditioned on paths leading to fixation.'],
  ['natural logarithm', 'The logarithm with base e, used to turn multiplicative changes into additive scale.'],
  ['exponential function', 'The inverse of the natural logarithm, often used to express multiplicative decay or growth.'],
  ['heterozygosity', 'The probability that two randomly sampled alleles at a locus are different.'],
  ['sweep-linked heterozygosity', 'Heterozygosity at a neutral locus linked to a selected site after a selective sweep.'],
  ['baseline heterozygosity', 'The reference heterozygosity level used before or without the sweep effect.'],
  ['expected heterozygosity', 'The expected level of genetic diversity, often measured by nucleotide diversity.'],
  ['decline in heterozygosity', 'The proportional reduction in genetic diversity relative to a reference level.'],
  ['recessive sweep recombination scale', 'A dimensionless parameter combining recombination, effective population size, and selection strength for a fully recessive sweep.'],
  ['characteristic dispersal length', 'The spatial length scale controlling how far the signal of a geographically structured sweep extends.'],
  ['extended selection gradient vector', 'Morrissey’s path-analysis selection gradient vector that incorporates indirect paths through the total-effect matrix.'],
  ['time-dependent distribution', 'A probability distribution indexed by time.'],
  ['inverse normalizing constant', 'The reciprocal of a constant that makes a probability distribution integrate to one.'],
  ['additive genetic value', 'The additive genetic contribution to an individual or trait value.'],
  ['total additive genetic value', 'The additive genetic value aggregated over a group or total phenotype.'],
  ['inclusive-fitness breeding value', 'A breeding value measured through inclusive-fitness effects.'],
  ['fitness breeding value', 'The additive genetic component associated with fitness.'],
  ['trait breeding value', 'The additive genetic component associated with the trait.'],
  ['mean trait breeding value', 'The population mean of the trait breeding value.'],
  ['estimated relationship matrix', 'An estimated matrix of genetic relationships between individuals.'],
  ['additive genetic component', 'A component representing additive genetic contribution in the model.'],
  ['power of additive matrix', 'A repeated product or power of an additive-genetic matrix.'],
  ['among-block variance', 'The variance among environmental or experimental blocks in stratified selection.'],
  ['genetic variance', 'The genetic component of phenotypic variance in the local quantitative-genetic model.'],
  ['within-block environmental variance', 'The residual environmental variance within blocks after stratification.'],
  ['class selection coefficient', 'A selection coefficient assigned to one class or genotype.'],
]);

export const CONCEPT_DEFINITIONS_ZH = new Map([
  ['wright-fisher transition probability', 'Wright-Fisher 模型中，群体从一个等位基因计数状态转移到另一个状态的概率。'],
  ['transition probability', '随机过程从一个状态进入另一个状态的概率。'],
  ['probability', '衡量某个事件或状态转移发生可能性的数量。'],
  ['population size', '模型中表示的个体数或基因拷贝数。'],
  ['count', '对个体、事件或类别数量的离散计数。'],
  ['variable', '公式中取值可以变化的占位量。'],
  ['time', '表示过程所处阶段、世代或时间间隔的量。'],
  ['mean', '相关分布或群体中某个量的平均值。'],
  ['delta', '模型中某个量的局部变化或增量。'],
  ['index', '用于标记类别、状态或求和项位置的下标。'],
  ['frequency', '某个类别或类型在群体中的相对占比。'],
  ['class frequency', '群体求和中某一类别或类型对应的频率。'],
  ['trait value', '表型或数量性状在模型中的数值。'],
  ['mean trait value', '群体中性状值的平均水平。'],
  ['class trait value', '某一类别或类型对应的性状值。'],
  ['fitness', '衡量个体繁殖成功或对下一代贡献的量。'],
  ['absolute fitness', '归一化之前、按绝对尺度衡量的适合度。'],
  ['mean fitness', '群体中适合度值的平均水平。'],
  ['fitness width', '控制性状偏离最优值时适合度下降速度的尺度参数。'],
  ['optimal trait value', '使适合度函数达到最大值的性状取值。'],
  ['strength of stabilizing selection', '描述稳定化选择把性状拉向最优值强度的参数。'],
  ['selection differential', '选择作用在遗传传递之前造成的平均性状值变化。'],
  ['response', '遗传或传递之后观察到的平均性状值变化。'],
  ['cumulative response', '随时间或世代累积得到的选择响应。'],
  ['cumulative selection differential', '随时间或世代累积得到的选择差。'],
  ['selected population', '受到选择处理的群体或品系。'],
  ['control population', '作为比较基线的对照组群体或对照品系。'],
  ['selected population mean trait value', '指定时间点中，选择组群体的观测平均性状值。'],
  ['control population mean trait value', '指定时间点中，对照组群体的观测平均性状值。'],
  ['variance', '衡量一个量围绕平均值分散程度的指标。'],
  ['covariance', '衡量两个量共同变化方向和强度的指标。'],
  ['expectation', '由概率分布预测出的平均值。'],
  ['likelihood', '衡量模型解释观测数据程度的量。'],
  ['coefficient', '控制公式中某一项大小的乘数。'],
  ['alpha', '局部模型中记为 alpha 的参数或分布形状参数。'],
  ['beta', '局部模型中记为 beta 的参数、回归系数或分布形状参数。'],
  ['standard deviation', '方差的平方根，用来表示分散程度的尺度。'],
  ['eigenvalue', '矩阵变换或相关结构中的特征值。'],
  ['identity matrix', '对角线为 1、其他位置为 0 的矩阵。'],
  ['parameter', '控制模型行为的未知量或固定量。'],
  ['parameter vector', '把多个模型参数作为一个向量整体表示。'],
  ['estimator', '用于估计未知参数的统计量。'],
  ['estimator vector', '用于同时估计多个参数的向量统计量。'],
  ['data vector', '以向量形式表示的观测数据。'],
  ['vector or matrix quantity', '以向量或矩阵形式表示的结构化数学量。'],
  ['covariance matrix', '描述多个变量方差和协方差的矩阵。'],
  ['wishart matrix', 'Wishart 或逆 Wishart 模型中使用的正定随机矩阵。'],
  ['order term', '描述表达式渐近规模的余项。'],
  ['distance', '衡量状态、数值或函数之间分离程度的量。'],
  ['function', '把输入映射为输出的规则。'],
  ['rate', '描述某个过程发生快慢的参数。'],
  ['selection coefficient', '衡量选择强度的参数。'],
  ['mutation rate', '衡量每一代发生突变概率的参数。'],
  ['recombination rate', '重组率表示连锁位点被重组分开的速率，决定中性位点逃离选择扫荡影响的机会。'],
  ['baseline recombination rate', '基准重组率用于给连锁位点效应定尺度，常作为比较遗传多样性下降幅度的参照。'],
  ['initial allele frequency', '初始等位基因频率表示过程开始时某个等位基因在群体中的相对占比。'],
  ['variance function', '描述扩散或随机过程中局部方差的函数。'],
  ['information', '衡量数据或似然函数对参数约束程度的量。'],
  ['bayes factor', '比较数据支持两个假设强弱的比值。'],
  ['fixation integral', '用于计算固定相关数量的积分。'],
  ['probability density', '连续变量中积分后得到概率的函数。'],
  ['pi constant', '圆周率 π，是解析表达式中使用的数学常数。'],
  ['stationary distribution', '在转移动力学下保持不变的概率分布。'],
  ['replacement-site divergence', '替换位点（会改变氨基酸的位点）在物种之间积累的分化量。'],
  ['silent-site divergence', '沉默位点在物种之间积累的分化量，常作为 MK 检验中的中性参照。'],
  ['replacement-site polymorphism', '物种内替换位点（会改变氨基酸的位点）的多态性数量。'],
  ['silent-site polymorphism', '物种内沉默位点的多态性数量，常作为中性多态性参照。'],
  ['replacement-site divergence per gene', '多基因 MK 类估计中，第 i 个基因的替换位点分化量。'],
  ['silent-site divergence per gene', '多基因 MK 类估计中，第 i 个基因的沉默位点分化量，作为中性分化参照。'],
  ['replacement-site polymorphism per gene', '多基因 MK 类估计中，第 i 个基因的替换位点多态性。'],
  ['silent-site polymorphism per gene', '多基因 MK 类估计中，第 i 个基因的沉默位点多态性，作为中性多态性参照。'],
  ['replacement-site segregating sites', '样本中替换位点的分离位点数量。'],
  ['silent-site segregating sites', '样本中沉默位点的分离位点数量。'],
  ['replacement-site mutation rate', '替换位点对应的突变率。'],
  ['silent-site mutation rate', '沉默位点对应的突变率。'],
  ['replacement-site theta', '替换位点对应的中性多样性参数 θ。'],
  ['silent-site theta', '沉默位点对应的中性多样性参数 θ。'],
  ['replacement-site count', '替换位点（会改变氨基酸的位点）的数量。'],
  ['silent-site count', '沉默位点的数量。'],
  ['neutral replacement substitutions', '中性基线下预期出现的替换位点替换数。'],
  ['adaptive replacement substitutions', '归因于适应性演化的替换位点替换数。'],
  ['estimated adaptive replacement substitutions', '对适应性替换位点替换数量的估计。'],
  ['estimated fraction of adaptive replacement substitutions', '对替换位点替换中适应性部分比例的估计。'],
  ['neutrality index', 'MK 检验中的赔率比，用来比较替换位点和沉默位点的多态性/分化比例。'],
  ['tarone-greenland neutrality index', 'Tarone-Greenland 加权中性指数，用来把多个基因的 MK 赔率比合并起来。'],
  ['direction of selection statistic', '方向选择统计量，用替换位点分化比例减去替换位点多态性比例来判断选择方向。'],
  ['estimated fraction of adaptive substitutions', '对替换中由适应性演化造成的比例进行估计的统计量。'],
  ['gamma function', '阶乘函数在连续情形下的推广。'],
  ['degrees of freedom', '控制 t 分布或卡方相关分布形状的参数。'],
  ['posterior degrees of freedom', '在观测数据条件化之后得到的自由度参数。'],
  ['acceptance rate', '采样算法中接受候选移动的概率或频率。'],
  ['monte carlo estimate', '由随机样本计算得到的估计值。'],
  ['estimated function', '由数据或模拟结果估计出的函数。'],
  ['loss-conditioned function', '在路径最终丢失这一条件下定义的函数。'],
  ['fixation-conditioned function', '在路径最终固定这一条件下定义的函数。'],
  ['natural logarithm', '以 e 为底的对数，用来把乘法关系转到可加尺度上。'],
  ['exponential function', '自然对数的反函数，常用来表示按比例衰减或增长。'],
  ['heterozygosity', '杂合度表示随机抽取两个等位基因时二者不同的概率，是衡量遗传多样性的核心量。'],
  ['sweep-linked heterozygosity', '选择扫荡后，与受选择位点连锁的中性位点仍保留下来的杂合度。'],
  ['baseline heterozygosity', '作为参照的杂合度水平，通常表示没有扫荡影响或扫荡前的遗传多样性。'],
  ['expected heterozygosity', '期望杂合度表示模型预期的遗传多样性水平，在这里用核苷酸多样性来衡量。'],
  ['decline in heterozygosity', '杂合度下降表示遗传多样性相对基准水平的减少比例。'],
  ['recessive sweep recombination scale', '完全隐性选择扫荡中的重组尺度参数，η = c√(4Ne/s)，用来衡量中性位点通过重组逃离扫荡影响的机会。'],
  ['characteristic dispersal length', '地理结构软扫荡模型中的特征扩散长度，用来刻画有利突变扩散时影响范围的空间尺度。'],
  ['extended selection gradient vector', 'Morrissey 路径分析中的扩展选择梯度向量，把直接路径系数通过总效应矩阵转换为包含间接路径的选择梯度。'],
  ['time-dependent distribution', '随时间变化的概率分布。'],
  ['inverse normalizing constant', '使概率分布积分为 1 的归一化常数的倒数。'],
  ['additive genetic value', '个体或性状值中的加性遗传贡献。'],
  ['total additive genetic value', '在群体或总表型中汇总的加性遗传值。'],
  ['inclusive-fitness breeding value', '通过包容适合度效应衡量的育种值。'],
  ['fitness breeding value', '与适合度相关的加性遗传组成部分。'],
  ['trait breeding value', '与性状相关的加性遗传组成部分。'],
  ['mean trait breeding value', '群体中性状育种值的平均水平。'],
  ['estimated relationship matrix', '估计得到的个体遗传关系矩阵。'],
  ['additive genetic component', '表示加性遗传贡献的模型组成部分。'],
  ['power of additive matrix', '加性遗传矩阵的幂或重复乘积。'],
  ['among-block variance', '分层选择中不同区组之间的环境或处理差异方差。'],
  ['genetic variance', '当前数量遗传模型中的遗传方差组成部分。'],
  ['within-block environmental variance', '分层后区组内部剩余的环境方差。'],
  ['class selection coefficient', '分配给某一类别或基因型的选择系数。'],
]);
